### ISSUE TITLE
Can't install wrangler on windows

### ISSUE THREAD

**Issue by winterssy** [cloudflare/wrangler#1622] opened 2020-10-29 14:28 UTC
#### Environment

* operating system: `Windows 10 20H2 19042.572`
* output of `node -v`: `v12.19.0`

#### Steps to reproduce

Run the install command via `npm`:

```
npm install -g @cloudflare/wrangler
```

#### What did you expect to see?

Install wrangler successfully

#### What did you see instead?

Here is the error log:
```
C:\Users\winter\scoop\persist\nodejs-lts\bin\wrangler -> C:\Users\winter\scoop\persist\nodejs-lts\bin\node_modules\@cloudflare\wrangler\run-wrangler.js

> @cloudflare/wrangler@1.12.0 postinstall C:\Users\winter\scoop\persist\nodejs-lts\bin\node_modules\@cloudflare\wrangler
> node ./install-wrangler.js

Downloading release https://workers.cloudflare.com/get-npm-wrangler-binary/1.12.0/x86_64-pc-windows-msvc
Error fetching release Request failed with status code 400
(node:9256) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (C:\Users\winter\scoop\persist\nodejs-lts\bin\node_modules\@cloudflare\wrangler\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\winter\scoop\persist\nodejs-lts\bin\node_modules\@cloudflare\wrangler\node_modules\axios\lib\core\settle.js:17:12)
    at RedirectableRequest.handleResponse (C:\Users\winter\scoop\persist\nodejs-lts\bin\node_modules\@cloudflare\wrangler\node_modules\axios\lib\adapters\http.js:210:9)
    at RedirectableRequest.emit (events.js:314:20)
    at RedirectableRequest._processResponse (C:\Users\winter\scoop\persist\nodejs-lts\bin\node_modules\@cloudflare\wrangler\node_modules\follow-redirects\index.js:269:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (C:\Users\winter\scoop\persist\nodejs-lts\bin\node_modules\@cloudflare\wrangler\node_modules\follow-redirects\index.js:50:10)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:602:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
(node:9256) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:9256) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
+ @cloudflare/wrangler@1.12.0
added 34 packages from 21 contributors in 6.554s
```

It seems it can't download `https://workers.cloudflare.com/get-npm-wrangler-binary/1.12.0/x86_64-pc-windows-msvc` but my network is ok and I can download it via Chrome browser directly. Anyone knows how to fix it? Thanks.

**Comment by nataliescottdavidson** [comment] 2020-10-30 15:58
Hey @winterssy, we had to deploy a hot fix last night so wrangler is now at 1.12.1. Not sure that the error is related to that (looks similar to an issue we had with getting rate limited where we pull artifacts in a worker). Would you mind trying `npm install -g @cloudflare/wrangler` one more time? Just tried it on windows and was successful.

**Comment by winterssy** [comment] 2020-10-31 00:15
So sad, the same problem:disappointed_relieved:
```
C:\Users\winter\scoop\persist\nodejs-lts\bin\wrangler -> C:\Users\winter\scoop\persist\nodejs-lts\bin\node_modules\@cloudflare\wrangler\run-wrangler.js

> @cloudflare/wrangler@1.12.1 postinstall C:\Users\winter\scoop\persist\nodejs-lts\bin\node_modules\@cloudflare\wrangler
> node ./install-wrangler.js

Downloading release https://workers.cloudflare.com/get-npm-wrangler-binary/1.12.1/x86_64-pc-windows-msvc
Error fetching release Request failed with status code 400
(node:16824) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (C:\Users\winter\scoop\persist\nodejs-lts\bin\node_modules\@cloudflare\wrangler\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\winter\scoop\persist\nodejs-lts\bin\node_modules\@cloudflare\wrangler\node_modules\axios\lib\core\settle.js:17:12)
    at RedirectableRequest.handleResponse (C:\Users\winter\scoop\persist\nodejs-lts\bin\node_modules\@cloudflare\wrangler\node_modules\axios\lib\adapters\http.js:210:9)
    at RedirectableRequest.emit (events.js:314:20)
    at RedirectableRequest._processResponse (C:\Users\winter\scoop\persist\nodejs-lts\bin\node_modules\@cloudflare\wrangler\node_modules\follow-redirects\index.js:269:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (C:\Users\winter\scoop\persist\nodejs-lts\bin\node_modules\@cloudflare\wrangler\node_modules\follow-redirects\index.js:50:10)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:602:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
(node:16824) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:16824) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
+ @cloudflare/wrangler@1.12.1
added 34 packages from 21 contributors in 4.369s
```

**Comment by SpriteOvO** [comment] 2021-08-11 10:31
I got the same problem. I can download the release from browser manually, but it always fails on **Linux** through **npm** or **yarn**, and the same with **npm** on **Windows**.

```
user:~$ sudo npm install -g @cloudflare/wrangler
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/@cloudflare/wrangler
npm ERR! command failed
npm ERR! command sh -c node ./install-wrangler.js
npm ERR! Downloading release from https://workers.cloudflare.com/get-npm-wrangler-binary/1.19.0/x86_64-unknown-linux-musl
npm ERR! Error fetching release: Request failed with status code 400

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-11T10_12_49_781Z-debug.log


user:~$ sudo yarn global add @cloudflare/wrangler
yarn global v1.22.11
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /usr/local/share/.config/yarn/global/node_modules/@cloudflare/wrangler: Command failed.
Exit code: 1
Command: node ./install-wrangler.js
Arguments: 
Directory: /usr/local/share/.config/yarn/global/node_modules/@cloudflare/wrangler
Output:
Downloading release from https://workers.cloudflare.com/get-npm-wrangler-binary/1.19.0/x86_64-unknown-linux-musl
Error fetching release: Request failed with status code 400
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

BTW, I'm using proxy and I've tried everything to set proxy in **npm** but nothing works.
I guess this is because **wrangler** doesn't download the release through the proxy, but directly.
https://github.com/cloudflare/wrangler/blob/99473b72b72f6251155f089f32fa8eeccbd1875f/npm/binary-install.js#L93-L104

It might be possible to solve the problem if the system proxy is used by default.
I'm not familiar with js development, but I can help test it if you guys need.

**Comment by SpriteOvO** [comment] 2021-08-14 13:33
After further investigation, the problem may not be caused by proxy, the installation didn't work for me anyway, so I had to build it locally to use it.

**Comment by petebacondarwin** [comment] 2022-06-21 09:17
Closing as there is a new version of Wrangler built on node.js, which should work fine on Windows.
Try installing the latest Wrangler (npm -g i wrangler@latest`). If you can reproduce the problem there, please open a new issue at https://github.com/cloudflare/wrangler2/issues/new/choose.

**Closed by petebacondarwin** 2022-06-21 09:17 UTC
Labels: regression, onboarding, os: windows, timed out
