### ISSUE TITLE
Send an api call to make sure global api key is valid.

### ISSUE THREAD

**Issue by scaria** [cloudflare/wrangler#678] opened 2019-09-23 17:42 UTC
Verify auth when you config api key with `wrangler configure`.

**Comment by EverlastingBugstopper** [comment] 2019-09-23 19:02
Hey @scaria thanks for the issue! I'm going to close this as a duplicate of https://github.com/cloudflare/wrangler/issues/439, you can keep track of updates there :)

**Closed by EverlastingBugstopper** 2019-09-23 19:02 UTC
Labels: user report
