### ISSUE TITLE
no prebuilt cargo-generate binaries are available for this platform - MacBook M1

### ISSUE THREAD

**Issue by ukd1** [cloudflare/wrangler#1742] opened 2021-01-20 23:11 UTC
This is very likely related to #1402, however it's a different platform, and the work around suggested in that issue did not work for me.

#### Environment

* operating system: macOS 11.0.1
* output of `rustc -V`: rustc 1.49.0 (e1884a8e3 2020-12-29)
* output of `node -v`: zsh: command not found: node
* output of `wrangler -V`:👷 ✨  wrangler 1.13.0
* contents of `wrangler.toml`: nil

#### Steps to reproduce

* fresh MacBook M1
* install rust ``curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh``
* ``cargo install wrangler``
* ``wrangler generate rustwasm-markdown-parser https://github.com/cloudflare/rustwasm-worker-template/`` (from https://developers.cloudflare.com/workers/tutorials/hello-world-rust)

#### What did you expect to see?
A templated example generated

#### What did you see instead?
```bash
% wrangler generate rustwasm-markdown-parser https://github.com/cloudflare/rustwasm-worker-template/
⬇️   Installing cargo-generate v0.5.0...
Error: could not download `cargo-generate`
no prebuilt cargo-generate binaries are available for this platform
```

I've tried:

```bash
cargo install --version 0.5.0 cargo-generate
```

this works...
```bash
% cargo generate --version
cargo-generate 0.5.0
```
but the error continues. I've tried copying the cargo-generate binary in to the wrangler cache folder as suggested in #1402, but nothing changes.

**Comment by yongfook** [comment] 2021-01-22 01:46
experiencing same issue

**Comment by HackettYu** [comment] 2021-02-08 07:33
I use npm 7.4.3 to generate the project, and it works on my machine(macbook M1).

Environment
- operating system: macOS 11.1.0
- output of rustc -V: rustc 1.49.0 (e1884a8e3 2020-12-29)
- output of node -v: v14.15.4
- output of usr/local/bin/wrangler -V:👷 ✨ wrangler 1.13.0
- output of ~/.cargo/bin/wrangler -V:👷 ✨ wrangler 1.13.0
- contents of wrangler.toml: nil

```bash
 /usr/local/bin/wrangler generate my-project https://github.com/cloudflare/worker-template
⬇️   Installing cargo-generate v0.5.0...
🔧   Creating project called `my-project`...
✨   Done! New project created /Users/hackettyu/repos/demo/cloudflare/my-project
...
````

but...

> https://github.com/cloudflare/wrangler#installation
>> If you are running an ARM based system (eg Raspberry Pi, Pinebook) you'll need to use the cargo installation method listed below to build wrangler from source.

**Comment by xtuc** [comment] 2021-02-08 09:04
Closing because it's a duplicate of https://github.com/cloudflare/wrangler/issues/1742

**Closed by xtuc** 2021-02-08 09:04 UTC
Labels: user report

**Comment by nilslice** [comment] 2021-04-27 15:49
This should be fixed in the latest release. Please give it a try and let us know if you still are hitting any errors:

`npm i -g @cloudflare/wrangler@1.16.1` or `cargo install wrangler --version 1.16.1`
