### ISSUE TITLE
Wrangler dev panic

### ISSUE THREAD

**Issue by dmitryyankowski** [cloudflare/wrangler#1554] opened 2020-09-10 19:33 UTC
#### Environment

* operating system: **Windows 10**
* output of `rustc -V`: **(Not avilable on Windows 10)**
* output of `node -v`: **v14.7.0**
* output of `wrangler -V`: **wrangler 1.11.0**
* contents of `wrangler.toml`

```
name = "mydomain-api-development"
type = "webpack"
account_id = "<my_account_id>"
zone_id = "<my_zone_id>"
webpack_config = "webpack.config.js"
workers_dev = true

[env.staging]
name = "mydomain-api-staging"
route = "https://staging.api.mydomain.com/*"

[env.production]
name = "mydomain-api-production"
route = "https://api.mydomain.com/*"
````

#### Steps to reproduce

1) Run `wrangler dev`

#### What did you expect to see?

No panic error.

#### What did you see instead?
```
[2020-09-10 11:34:05] GET mydomain-api-development.mydomain.workers.dev/ HTTP/1.1 200 OK
[2020-09-10 11:34:06] GET mydomain-api-development.mydomain.workers.dev/ HTTP/1.1 200 OK
thread 'tokio-runtime-worker' panicked at 'Failed to connect to devtools instance: Http(400)', src\commands\dev\socket.rs:26:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: panic
```

**Comment by danbars** [comment] 2020-10-08 20:17
I also get wrangler dev panic all the time.
It doesn't happen in production (as far as I know)
It is pretty annoying and pretty common.

**Comment by davidbarratt** [comment] 2020-10-11 18:48
This seems like a duplicate of #1510?

**Comment by nataliescottdavidson** [comment] 2020-10-20 19:55
Closing as duplicate of #1510

**Closed by nataliescottdavidson** 2020-10-20 19:55 UTC
Labels: bug, status - needs repro, subject - wrangler dev, user report
