### ISSUE TITLE
reqwest::Error panics the thread 

### ISSUE THREAD

**Issue by ycd** [cloudflare/wrangler#1743] opened 2021-01-21 11:54 UTC
#### Environment

* operating system: Arch Linux 
* output of `rustc -V`: rustc 1.48.0 (7eac88abb 2020-11-16)
* output of `node -v`: v15.6.0
* output of `wrangler -V`: wrangler 1.13.0

#### Steps to reproduce

 1. Installed wrangler with `cargo install wrangler`
 1. When i run the `wrangler` for the first time. I got segmentation fault and sadly i `clear`ed it and i wasn't able to reproduce it back either.
 1. Then i ran `wrangler help`
 1. I got the following error:
 
```rust
thread '<unnamed>' panicked at 'Client::new(): reqwest::Error { kind: Builder, source: Normal(ErrorStack([])) }', /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.10/src/blocking/client.rs:618:38
```

I'm facing this error for all the commands that i run.

 5. I used `export RUST_BACKTRACE=1` to trace error however `stack backtrace` comes empty.
 ```
 stack backtrace:
```
 

#### What did you expect to see?

```
➜  ~ wrangler -V
👷 ✨  wrangler 1.13.0  
```

#### What did you see instead?

```
➜  ~ wrangler -V
👷 ✨  wrangler 1.13.0
thread '<unnamed>' panicked at 'Client::new(): reqwest::Error { kind: Builder, source: Normal(ErrorStack([])) }', /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.10/src/blocking/client.rs:618:38%     
```

**Comment by mxdpeep** [comment] 2021-02-03 15:03
Debian 9

# rustc --version
rustc 1.49.0 (e1884a8e3 2020-12-29)
# uname -r
4.19.0-14-amd64
# wrangler -V
👷 ✨  wrangler 1.13.0
thread '<unnamed>' panicked at 'Client::new(): reqwest::Error { kind: Builder, source: Normal(ErrorStack([])) }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.10/src/blocking/client.rs:618:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by ags799** [comment] 2021-02-03 19:54
[Looks like it's a bad idea to use `Client::new`.](https://docs.rs/reqwest/0.10.10/src/reqwest/async_impl/client.rs.html#951)

I submitted #1750 to stop panicking here and start giving an error message. Hopefully that will add some context.

**Comment by xortive** [comment] 2021-02-24 21:26
this is related to us using musl in CI, since it's impossible to reproduce locally without the musl target. folks running into this can use the `cargo install wrangler` method if it's preventing them from using wrangler for now, but we should disable using musl in CI soon

**Comment by xortive** [comment] 2021-02-24 22:27
closing as dupe of #1464 (which I will reopen)

**Closed by xortive** 2021-02-24 22:27 UTC
Labels: bug

**Comment by llbbl** [comment] 2021-02-27 23:39
happening for me after fresh install of wrangler using bash. when I switch back to zsh it works fine thou.

```
thread '<unnamed>' panicked at 'Client::new(): reqwest::Error { kind: Builder, source: Normal(ErrorStack([])) }', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.10/src/blocking/client.rs:618:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

just running wrangler --version
