### ISSUE TITLE
wrangler dev (You have not provided your Cloudflare credentials)

### ISSUE THREAD

**Issue by Froxz** [cloudflare/wrangler#1978] opened 2021-07-01 07:06 UTC
#### Describe the bug

wrangler says:

"You have not provided your Cloudflare credentials.
Please run `wrangler login`, `wrangler config`, or visit"

Running wrangler login or manually wrangler config set the token correctly (I can see it %USER%\.wrangler\config\default.toml)

Also running wrangler whoami, shows correct Account ID and email connected.

#### Expected behavior

After wrangler login / config to connect to account id to use KV.

#### Environment and versions

Fill out the following information about your environment.

* operating system: Windows 10
* output of `wrangler -V`: wrangler 1.17.0
* output of `node -v`: v14.17.0
* content of `wrangler.toml`: 
 
```yaml
name = "services-dev"
type = "webpack"
account_id = "ACCOUNT ID HERE"
workers_dev = true
webpack_config = "webpack.dev.js"
kv_namespaces = [
  { binding = "HELPERS", id = "ID HERE", preview_id = "ID HERE" }
]

[env.stage]
name = "services-stage"
webpack_config = "webpack.production.js"
kv_namespaces = [
  { binding = "HELPERS", id = "ID HERE", preview_id = "ID HERE" }
]

[env.production]
name = "services-production"
webpack_config = "webpack.production.js"
kv_namespaces = [
  { binding = "HELPERS", id = "ID HERE", preview_id = "ID HERE" }
]
```

**Comment by nilslice** [comment] 2021-07-02 20:37
Thanks, @Froxz - sorry you're hitting this. Are you able to publish Workers to your account using the same credentials you're trying to run `dev` with?

**Comment by Froxz** [comment] 2021-07-05 06:57
Hi @nilslice 

I just tested I'm able to push the script to CF:

```bash
wrangler publish --env=stage

 Built successfully, built project size is 33 KiB.
 Successfully published your script to
 https://***.workers.dev```

**Comment by Froxz** [comment] 2021-07-05 07:04
Hi @nilslice 

some more info:

If I run `wrangler dev` (without --host) parameter I don't get this error, but accesing `http://127.0.0.1:8787` gives me: There is nothing here yet.

I tried to publish the dev into CF, the publish workes fine but, still see 404.

running with `--host` param brings the error back.

**Comment by Froxz** [comment] 2021-07-05 07:16
Hi @nilslice 

ok I think I missed this `--host provided, will run unauthenticated and upstream to provided host
unauthenticated`.


Ok then question how can I test on my local with custom hostname using KV ?

**Comment by nilslice** [comment] 2021-07-06 16:24
Hey @Froxz - 

That's a good question. I'll have to try this out on my own and see how to reproduce.

**Comment by fikisipi** [comment] 2021-07-23 10:49
@nilslice What works for me is using a production `preview_id`. Suppose I use a short fake `preview_id` as in the guide:
```
kv_namespaces = [
    { binding = "example", id = "<redacted>",
      preview_id = "faaf" }
]
```
Notice that `preview_id = "faaf"`. I get this running `wrangler dev`: ❌

```
~ wrangler dev
Error: HTTP status client error (400 Bad Request) for url
(https://api.cloudflare.com/client/v4/accounts/workers/scripts/myproject/edge-preview)
```

------

If I change `preview_id = <32 byte real hex string>`, it does work ✔️

```
~ wrangler dev
Listening on http://127.0.0.1:8787
```

**Comment by Froxz** [comment] 2021-07-23 12:10
Hi @fikisipi 

it does works `wrangler dev` but doesn't if you specify --host.

**Comment by tsmith512** [comment] 2021-08-06 20:26
Howdy! I have also run into this. If I specify the `--host` parameter, I get the "You have not provided your Cloudflare credentials." error. Just to be sure, I re-authed on a new API Key. I am able to publish the worker script and list/put secrets.

Unfortunately, running `wrangler dev` without the host flag ends up hitting a Page Rule that does a domain redirect `example.com --> www.example.com`, so requests to 127.0.0.1 get bounced to the production Worker.

(Ubuntu 20.04 on Windows WSL2, Wrangler 1.19.0, Node 10.24.1)

**Comment by Froxz** [comment] 2021-08-07 23:08
@nilslice Any updates on this? (For info on wrangler@10 everything was working fine, it is safe to downgrade?

**Comment by rmontgomery429** [comment] 2021-08-28 14:00
For some additional context, this also affects KV store use and has been reported as such here: https://github.com/cloudflare/wrangler/issues/1866

The source of the bug appears to originate from this PR: https://github.com/cloudflare/wrangler/pull/1498

**Comment by rmontgomery429** [comment] 2021-08-28 14:08
While this bug may be a feature at the very least the messaging is confusing.

```
$ wrangler dev --host 127.0.0.1:8080
⚠️  --host provided, will run unauthenticated and upstream to provided host
unauthenticated
You have not provided your Cloudflare credentials.

Please run `wrangler login`, `wrangler config`, or visit
https://developers.cloudflare.com/workers/tooling/wrangler/configuration/#using-environment-variables
for info on authenticating with environment variables.
💁  Running preview without authentication.
⚠️  KV Namespaces are not supported in preview without setting API credentials and account_id
👂  Listening on http://127.0.0.1:8787
```

Wrangler decided to ignore the authentication intentionally but the messages provided seem to indicate that the user is at fault and has not performed authentication and should do so. No matter how many times a user performs `wrangler login`, or `wrangler config` or sets an environment variable, this will not rectify the situation.

**Comment by Froxz** [comment] 2021-09-07 06:30
Hi @nilslice do you have any suggestions/updates?

Is really an obstacle for us for local development and testing as we can't preview. (have always to publish to stage fix errors if any and again).

We use CF Workers mostly to inject/rewrite data on the page.

**Comment by threepointone** [comment] 2021-09-08 13:01
Hiya, I'll bring this up with the team and get back to you.

**Comment by threepointone** [comment] 2022-05-18 13:41
wrangler v2 has fixed this pretty throughly now. Closing this issue.

**Closed by threepointone** 2022-05-18 13:41 UTC
Labels: bug

**Comment by Froxz** [comment] 2022-05-18 13:43
@threepointone wrangler 2 is stable? should we migrate to wrangler 2?

**Comment by threepointone** [comment] 2022-05-18 13:47
Yes! I recommend you try it on a couple of non critical projects and deploy to a staging env first, since it is after all pretty new and has a couple of breaking changes. But we're actively encouraging people to migrate. You can try it out today with `npm install wrangler` (note the lack of the `@cloudflare` scope). We're currently tracking the project here https://github.com/cloudflare/wrangler2 but we'll merge it into this repo in the near future.
