### ISSUE TITLE
`cargo install wrangler --force` failing with compilation errors

### ISSUE THREAD

**Issue by geelen** [cloudflare/wrangler#2081] opened 2021-09-20 10:51 UTC
#### Describe the bug

Was prompted to update wrangler, checked and it was previously installed in `/Users/glen/.cargo/bin/wrangler` so I followed the instructions for a Cargo upgrade:

```
cargo install wrangler --force
```

Got three compilation errors:

```
error[E0658]: or-patterns syntax is experimental
error[E0658]: use of unstable library feature 'str_split_once': newly added
error[E0277]: `[&str; 8]` is not an iterator
```

Full error output:

<details>

```
❯ cargo install wrangler --force
    Updating crates.io index
  Downloaded wrangler v1.19.3
  Downloaded 1 crate (970.8 KB) in 0.70s
  Installing wrangler v1.19.3
  Downloaded combine v4.6.1
  Downloaded futures-channel v0.3.17
  Downloaded itoa v0.4.8
  Downloaded cpufeatures v0.2.1
  Downloaded pin-project-lite v0.2.7
  Downloaded cc v1.0.70
  Downloaded async-trait v0.1.51
  Downloaded arc-swap v1.4.0
  Downloaded cloudflare v0.8.7
  Downloaded bitflags v1.3.2
  Downloaded libc v0.2.102
  Downloaded backtrace v0.3.61
  Downloaded futures v0.3.17
  Downloaded difflib v0.4.0
  Downloaded flate2 v1.0.22
  Downloaded matches v0.1.9
  Downloaded openssl-sys v0.9.66
  Downloaded indexmap v1.7.0
  Downloaded native-tls v0.2.8
  Downloaded mio v0.7.13
  Downloaded memchr v2.4.1
  Downloaded parity-ws v0.11.0
  Downloaded bzip2-sys v0.1.11+1.0.8
  Downloaded libflate v1.1.1
  Downloaded futures-macro v0.3.17
  Downloaded ipnet v2.3.1
  Downloaded httparse v1.5.1
  Downloaded http-body v0.4.3
  Downloaded tar v0.4.37
  Downloaded sha-1 v0.9.8
  Downloaded serde_path_to_error v0.1.5
  Downloaded tokio-util v0.6.8
  Downloaded text_io v0.1.9
  Downloaded tokio-macros v1.3.0
  Downloaded thiserror v1.0.29
  Downloaded sha2 v0.9.8
  Downloaded tokio-stream v0.1.7
  Downloaded structopt-derive v0.4.16
  Downloaded object v0.26.2
  Downloaded serde v1.0.130
  Downloaded twox-hash v1.6.1
  Downloaded unicode-bidi v0.3.6
  Downloaded tracing-core v0.1.20
  Downloaded synstructure v0.12.5
  Downloaded webpki-roots v0.21.1
  Downloaded serde_with_macros v1.5.0
  Downloaded serde_json v1.0.68
  Downloaded gimli v0.25.0
  Downloaded serde_derive v1.0.130
  Downloaded unicode-width v0.1.9
  Downloaded typenum v1.14.0
  Downloaded which v4.2.2
  Downloaded xml-rs v0.8.4
  Downloaded tokio v1.11.0
  Downloaded syn v1.0.76
  Downloaded chrome-devtools-rs v0.0.0-alpha.3
  Downloaded structopt v0.3.23
  Downloaded tinyvec v1.4.0
  Downloaded thiserror-impl v1.0.29
  Downloaded openssl v0.10.36
  Downloaded serde_with v1.10.0
  Downloaded slog-async v2.7.0
  Downloaded tracing v0.1.28
  Downloaded siphasher v0.3.7
  Downloaded reqwest v0.11.4
  Downloaded oauth2 v4.1.0
  Downloaded semver v1.0.4
  Downloaded socket2 v0.4.2
  Downloaded curl-sys v0.4.47+curl-7.79.0
  Downloaded openssl-src v111.16.0+1.1.1l
  Downloaded proc-macro2 v1.0.29
  Downloaded pin-project v1.0.8
  Downloaded slab v0.4.4
  Downloaded rustc-demangle v0.1.21
  Downloaded pin-project-internal v1.0.8
  Downloaded predicates v2.0.2
  Downloaded float-cmp v0.9.0
  Downloaded security-framework-sys v2.4.2
  Downloaded security-framework v2.4.2
  Downloaded ignore v0.4.18
  Downloaded hyper v0.14.13
  Downloaded h2 v0.3.4
  Downloaded globset v0.4.8
  Downloaded futures-task v0.3.17
  Downloaded futures-executor v0.3.17
  Downloaded futures-core v0.3.17
  Downloaded futures-util v0.3.17
  Downloaded futures-io v0.3.17
  Downloaded colored_json v2.1.0
  Downloaded filetime v0.2.15
  Downloaded bzip2 v0.4.3
  Downloaded bytes v1.1.0
  Downloaded ansi_term v0.12.1
  Downloaded anyhow v1.0.44
  Downloaded addr2line v0.16.0
  Downloaded futures-sink v0.3.17
  Downloaded erased-serde v0.3.16
  Downloaded 97 crates (14.9 MB) in 3.84s (largest was `openssl-src` at 5.1 MB)
   Compiling libc v0.2.102
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.29
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.76
   Compiling autocfg v1.0.1
   Compiling memchr v2.4.1
   Compiling cc v1.0.70
   Compiling version_check v0.9.3
   Compiling lazy_static v1.4.0
   Compiling log v0.4.14
   Compiling serde_derive v1.0.130
   Compiling serde v1.0.130
   Compiling bytes v1.1.0
   Compiling once_cell v1.8.0
   Compiling pkg-config v0.3.19
   Compiling pin-project-lite v0.2.7
   Compiling bitflags v1.3.2
   Compiling itoa v0.4.8
   Compiling regex-syntax v0.6.25
   Compiling ppv-lite86 v0.2.10
   Compiling futures-core v0.3.17
   Compiling typenum v1.14.0
   Compiling core-foundation-sys v0.8.2
   Compiling proc-macro-hack v0.5.19
   Compiling ryu v1.0.5
   Compiling slab v0.4.4
   Compiling futures-sink v0.3.17
   Compiling futures-task v0.3.17
   Compiling fnv v1.0.7
   Compiling futures-channel v0.3.17
   Compiling byteorder v1.4.3
   Compiling proc-macro-nested v0.1.7
   Compiling untrusted v0.7.1
   Compiling spin v0.5.2
   Compiling httparse v1.5.1
   Compiling futures-io v0.3.17
   Compiling adler v1.0.2
   Compiling pin-utils v0.1.0
   Compiling hashbrown v0.11.2
   Compiling tinyvec_macros v0.1.0
   Compiling unicode-width v0.1.9
   Compiling matches v0.1.9
   Compiling base64 v0.13.0
   Compiling remove_dir_all v0.5.3
   Compiling gimli v0.25.0
   Compiling native-tls v0.2.8
   Compiling percent-encoding v2.1.0
   Compiling slog v2.7.0
   Compiling unicode-bidi v0.3.6
   Compiling serde_json v1.0.68
   Compiling rustc-demangle v0.1.21
   Compiling crc32fast v1.2.1
   Compiling crossbeam-utils v0.8.5
   Compiling cfg-if v0.1.10
   Compiling try-lock v0.2.3
   Compiling httpdate v1.0.1
   Compiling ident_case v1.0.1
   Compiling tower-service v0.3.1
   Compiling strsim v0.10.0
   Compiling getrandom v0.1.16
   Compiling opaque-debug v0.3.0
   Compiling cpufeatures v0.2.1
   Compiling regex-automata v0.1.10
   Compiling encoding_rs v0.8.28
   Compiling rustversion v1.0.5
   Compiling failure_derive v0.1.8
   Compiling rle-decode-fast v1.0.1
   Compiling slog-async v2.7.0
   Compiling mime v0.3.16
   Compiling static_assertions v1.1.0
   Compiling byte-tools v0.3.1
   Compiling anyhow v1.0.44
   Compiling lexical-core v0.7.6
   Compiling arc-swap v1.4.0
   Compiling either v1.6.1
   Compiling safemem v0.3.3
   Compiling linked-hash-map v0.5.4
   Compiling take_mut v0.2.2
   Compiling adler32 v1.2.0
   Compiling curl v0.4.38
   Compiling ipnet v2.3.1
   Compiling unicode-segmentation v1.8.0
   Compiling arrayvec v0.5.2
   Compiling same-file v1.0.6
   Compiling async-trait v0.1.51
   Compiling fake-simd v0.1.2
   Compiling strsim v0.8.0
   Compiling ansi_term v0.11.0
   Compiling serde v0.8.23
   Compiling data-encoding v2.3.2
   Compiling erased-serde v0.3.16
   Compiling foreign-types-shared v0.1.1
   Compiling xml-rs v0.8.4
   Compiling opaque-debug v0.2.3
   Compiling percent-encoding v1.0.1
   Compiling openssl v0.10.36
   Compiling semver v1.0.4
   Compiling utf-8 v0.7.6
   Compiling vec_map v0.8.2
   Compiling lazycell v1.3.0
   Compiling encode_unicode v0.3.6
   Compiling termcolor v1.1.2
   Compiling rust-ini v0.13.0
   Compiling hex v0.4.3
   Compiling predicates-core v1.0.2
   Compiling difflib v0.4.0
   Compiling unescape v0.1.0
   Compiling humantime v2.1.0
   Compiling siphasher v0.3.7
   Compiling ansi_term v0.12.1
   Compiling is_executable v0.1.2
   Compiling number_prefix v0.3.0
   Compiling normalize-line-endings v0.3.0
   Compiling path-slash v0.1.4
   Compiling number_prefix v0.4.0
   Compiling text_io v0.1.9
   Compiling tracing-core v0.1.20
   Compiling thread_local v1.1.3
   Compiling unicase v2.6.0
   Compiling generic-array v0.14.4
   Compiling proc-macro-error-attr v1.0.4
   Compiling error-chain v0.12.4
   Compiling proc-macro-error v1.0.4
   Compiling nom v5.1.2
   Compiling num-traits v0.2.14
   Compiling tokio v1.11.0
   Compiling futures-macro v0.3.17
   Compiling futures-util v0.3.17
   Compiling miniz_oxide v0.4.4
   Compiling indexmap v1.7.0
   Compiling num-integer v0.1.44
   Compiling openssl-src v111.16.0+1.1.1l
   Compiling input_buffer v0.4.0
   Compiling http v0.2.4
   Compiling tinyvec v1.4.0
   Compiling textwrap v0.11.0
   Compiling base64 v0.10.1
   Compiling form_urlencoded v1.0.1
   Compiling ring v0.16.20
   Compiling backtrace v0.3.61
   Compiling libz-sys v1.1.3
   Compiling bzip2-sys v0.1.11+1.0.8
   Compiling curl-sys v0.4.47+curl-7.79.0
   Compiling sys-info v0.9.0
   Compiling libflate_lz77 v1.1.0
   Compiling block-padding v0.1.5
   Compiling line-wrap v0.1.1
   Compiling itertools v0.10.1
   Compiling yaml-rust v0.4.5
   Compiling walkdir v2.3.2
   Compiling heck v0.3.3
   Compiling foreign-types v0.3.2
   Compiling addr2line v0.16.0
   Compiling tracing v0.1.28
   Compiling openssl-sys v0.9.66
   Compiling unicode-normalization v0.1.19
   Compiling want v0.3.0
   Compiling log v0.3.9
   Compiling http-body v0.4.3
   Compiling aho-corasick v0.7.18
   Compiling object v0.26.2
   Compiling csv-core v0.1.10
   Compiling combine v4.6.1
   Compiling getrandom v0.2.3
   Compiling signal-hook-registry v1.4.0
   Compiling mio v0.7.13
   Compiling num_cpus v1.13.0
   Compiling time v0.1.44
   Compiling atty v0.2.14
   Compiling socket2 v0.4.2
   Compiling dirs-sys-next v0.1.2
   Compiling iovec v0.1.4
   Compiling terminal_size v0.1.17
   Compiling termios v0.3.3
   Compiling dirs-sys v0.3.6
   Compiling net2 v0.2.37
   Compiling filetime v0.2.15
   Compiling dirs v1.0.5
   Compiling xattr v0.2.2
   Compiling fsevent-sys v2.0.1
   Compiling clicolors-control v1.0.1
   Compiling term_size v0.3.2
   Compiling fs2 v0.4.3
   Compiling which v4.2.2
   Compiling quote v1.0.9
   Compiling core-foundation v0.9.1
   Compiling security-framework-sys v2.4.2
   Compiling libflate v1.1.1
   Compiling slog-scope v4.4.0
   Compiling crossbeam-channel v0.5.1
   Compiling generic-array v0.12.4
   Compiling rand_core v0.6.3
   Compiling idna v0.2.3
   Compiling regex v1.5.4
   Compiling clap v2.33.3
   Compiling dirs-next v2.0.0
   Compiling syncbox v0.2.4
   Compiling bytes v0.4.12
   Compiling rand_core v0.5.1
   Compiling dirs v2.0.2
   Compiling dirs v3.0.2
   Compiling mio v0.6.23
   Compiling term v0.5.2
   Compiling tar v0.4.37
   Compiling fsevent v0.4.0
   Compiling mime_guess v2.0.3
   Compiling security-framework v2.4.2
   Compiling slog-stdlog v4.1.0
   Compiling flate2 v1.0.22
   Compiling num-traits v0.1.43
   Compiling float-cmp v0.9.0
   Compiling block-buffer v0.7.3
   Compiling digest v0.8.1
   Compiling digest v0.9.0
   Compiling block-buffer v0.9.0
   Compiling rand_chacha v0.3.1
   Compiling bzip2 v0.4.3
   Compiling term v0.7.0
   Compiling eventual v0.1.7
   Compiling rand_chacha v0.2.2
   Compiling slog-kvfilter v0.7.0
   Compiling console v0.9.2
   Compiling console v0.11.3
   Compiling console v0.14.1
   Compiling env_logger v0.8.4
   Compiling mio-extras v2.0.6
   Compiling notify v4.0.17
   Compiling serde-hjson v0.9.1
   Compiling predicates v2.0.2
   Compiling sha-1 v0.8.2
   Compiling sha-1 v0.9.8
   Compiling sha2 v0.9.8
   Compiling rand v0.8.4
   Compiling rand v0.7.3
   Compiling indicatif v0.15.0
   Compiling darling_core v0.13.0
   Compiling synstructure v0.12.5
   Compiling webpki v0.21.4
   Compiling sct v0.6.1
   Compiling tokio-macros v1.3.0
   Compiling thiserror-impl v1.0.29
   Compiling trackable_derive v1.0.0
   Compiling pin-project-internal v1.0.8
   Compiling tempfile v3.2.0
   Compiling twox-hash v1.6.1
   Compiling structopt-derive v0.4.16
   Compiling ct-logs v0.8.0
   Compiling rustls v0.19.1
   Compiling webpki-roots v0.21.1
   Compiling trackable v1.2.0
   Compiling thiserror v1.0.29
   Compiling darling_macro v0.13.0
   Compiling pin-project v1.0.8
   Compiling zip v0.5.13
   Compiling billboard v0.1.0
   Compiling failure v0.1.8
   Compiling darling v0.13.0
   Compiling structopt v0.3.23
   Compiling binary-install v0.0.3-alpha.1
   Compiling serde_with_macros v1.5.0
   Compiling rustls-native-certs v0.5.0
   Compiling tokio-util v0.6.8
   Compiling tokio-native-tls v0.3.0
   Compiling tokio-rustls v0.22.0
   Compiling tokio-stream v0.1.7
   Compiling tokio-retry v0.3.0
   Compiling futures-executor v0.3.17
   Compiling h2 v0.3.4
   Compiling futures v0.3.17
   Compiling chrono v0.4.19
   Compiling url v2.2.2
   Compiling bstr v0.2.16
   Compiling serde_urlencoded v0.7.0
   Compiling serde_path_to_error v0.1.5
   Compiling serde_with v1.10.0
   Compiling serde_qs v0.4.6
   Compiling uuid v0.8.2
   Compiling toml v0.5.8
   Compiling tungstenite v0.13.0
   Compiling parity-ws v0.11.0
   Compiling globset v0.4.8
   Compiling csv v1.1.6
   Compiling slog-term v2.8.0
   Compiling plist v0.5.5
   Compiling toml_edit v0.2.1
   Compiling chrome-devtools-rs v0.0.0-alpha.3
   Compiling colored_json v2.1.0
   Compiling config v0.11.0
   Compiling tokio-tungstenite v0.14.0
   Compiling ignore v0.4.18
   Compiling sloggers v1.0.1
   Compiling prettytable-rs v0.8.0
   Compiling os-version v0.1.1
   Compiling hyper v0.14.13
   Compiling hyper-tls v0.5.0
   Compiling hyper-rustls v0.22.1
   Compiling reqwest v0.11.4
   Compiling cloudflare v0.8.7
   Compiling oauth2 v4.1.0
   Compiling wrangler v1.19.3
error[E0658]: or-patterns syntax is experimental
   --> /Users/glen/.cargo/registry/src/github.com-1ecc6299db9ec823/wrangler-1.19.3/src/commands/dev/socket.rs:228:21
    |
228 | /                     Error::ConnectionClosed
229 | |                     | Error::Protocol(ProtocolError::ResetWithoutClosingHandshake),
    | |__________________________________________________________________________________^
    |
    = note: see issue #54883 <https://github.com/rust-lang/rust/issues/54883> for more information

error[E0658]: or-patterns syntax is experimental
   --> /Users/glen/.cargo/registry/src/github.com-1ecc6299db9ec823/wrangler-1.19.3/src/commands/tail/websocket.rs:178:17
    |
178 |             Err(AlreadyClosed | ConnectionClosed) => Ok(()),
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #54883 <https://github.com/rust-lang/rust/issues/54883> for more information

error[E0658]: use of unstable library feature 'str_split_once': newly added
  --> /Users/glen/.cargo/registry/src/github.com-1ecc6299db9ec823/wrangler-1.19.3/src/commands/tail/filter.rs:75:22
   |
75 |         match header.split_once(":") {
   |                      ^^^^^^^^^^
   |
   = note: see issue #74773 <https://github.com/rust-lang/rust/issues/74773> for more information

error[E0277]: `[&str; 8]` is not an iterator
  --> /Users/glen/.cargo/registry/src/github.com-1ecc6299db9ec823/wrangler-1.19.3/src/login/mod.rs:51:22
   |
51 |         for scope in SCOPES_LIST {
   |                      ^^^^^^^^^^^ borrow the array with `&` or call `.iter()` on it to iterate over it
   |
   = help: the trait `Iterator` is not implemented for `[&str; 8]`
   = note: arrays are not iterators, but slices like the following are: `&[1, 2, 3]`
   = note: required because of the requirements on the impl of `IntoIterator` for `[&str; 8]`
   = note: required by `into_iter`

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0277, E0658.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `wrangler`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `wrangler v1.19.3`, intermediate artifacts can be found at `/var/folders/3f/fwp6mt7n13bfnkd5vl3jmh1w0000gp/T/cargo-installz4y8BD`

Caused by:
  build failed
```

</details>

#### Reproduce the bug

No idea how to reproduce, hope the bug report is obvious to a Rust dev.

#### Expected behavior

Wrangler to be installed.

#### Environment and versions

Fill out the following information about your environment.

* operating system: Big Sur 11.5.2
* output of `wrangler -V`: `wrangler 1.17.0`
* output of `node -v`: `v16.3.0`
* content of `wrangler.toml`: N/A, was only trying to run `wrangler generate`.

```
❯ cargo -V
cargo 1.49.0 (d00d64df9 2020-12-05)
```

**Comment by jyn514** [comment] 2021-09-20 16:35
Duplicate of https://github.com/cloudflare/wrangler/issues/2076.

**Closed by jyn514** 2021-09-20 16:35 UTC
Labels: bug
