### ISSUE TITLE
Don't use Config crate

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#867] opened 2019-11-13 16:31 UTC
It's introducing bugs like #704 and it's also [no longer maintained](https://github.com/mehcode/config-rs/issues/111). EDIT: development seems to have continued, but stagnated just a bit, I still think we should move to our own handling since our use case is straigthforward

We really only use it for merging environment variables with our manifest configuration, which we should be able to do in house by combining `std::env` `toml` and `serde`

Instead of looping over all environment vairables looking for a prefix, we should loop over a whitelist of our supported environment variables.

When constructing `GlobalUser`, we should loop over CF_API_TOKEN, CF_EMAIL, and CF_API_KEY.

When constructing `Manifest`, we should loop over CF_ZONE_ID, CF_ACCOUNT_ID, CF_NAME, CF_TYPE, CF_WORKERS_DEV, CF_ROUTE, and CF_WEBPACK_CONFIG. Note that this leaves out CF_ENV, CF_ROUTES, CF_KV_NAMESPACES, and CF_SITE which we currently try to parse. These are not strings and cannot be set in an environment variable, so we should not attempt to parse them. This will eliminate the parsing bug seen in #704 and will also (very slightly) improve performance on machines with a large number of environment variables.

This refactor would also have the benefit of making our code more readable and easier to document which environment variables are officially supported.

**Comment by ashleymichal** [comment] 2020-05-14 21:09
there is a struct for this...

**Comment by EverlastingBugstopper** [comment] 2020-05-14 21:25
i believe i opened this issue before there was - mind updating to point folks at the right place to start for this one?

**Comment by ashleymichal** [comment] 2020-05-14 21:49
we could mark  as duplicate of https://github.com/cloudflare/wrangler/issues/852

**Closed** 2020-05-15 19:53 UTC
Labels: category - refactor, status - PR welcome
