### ISSUE TITLE
Remove dist_to_clean from wrangler cleanup steps

### ISSUE THREAD

**Issue by zackbloom** [cloudflare/wrangler#255] opened 2019-06-14 22:59 UTC
Hello! I attempted to run a preview on a project I was working on. This project has an independent webpack build, so I configured webpack to output to an index.js file in the root of the project and copied over a wrangler.toml file from the generator. When I went to preview, Wrangler deleted my dev directory, erasing any of the files I didn't have open elsewhere.

![image](https://user-images.githubusercontent.com/55347/59542876-011aaf80-8ebd-11e9-994a-4e0bfffbebcb.png)

**Comment by xtuc** [comment] 2019-06-15 09:39
Which dev directory did you use? `./worker` will currently be removed I believe (that's a bug).

**Comment by zackbloom** [comment] 2019-06-15 17:48
The project I copied the template from was called "worker", but this folder was named "afs".

**Comment by xtuc** [comment] 2019-06-15 17:59
This is really strange, would we mind chatting on gchat?

**Comment by victoriabernard92** [comment] 2019-06-17 11:05
Is this resolved? it seemed the directory checked was `af` and not `afs` ?

**Comment by zackbloom** [comment] 2019-06-17 14:57
Oh you're just seeing an artifact of my tab-completion attempt there, the folder was gone. Existing editor sessions couldn't save even after I recreated the folder.

**Comment by zackbloom** [comment] 2019-06-18 00:44
@xtuc Sure! I'll be around tomorrow or find a time on my calendar.

**Comment by ashleygwilliams** [comment] 2019-06-21 13:46
@zackbloom can you link to a repo that we could use to reproduce? thanks!

**Comment by zackbloom** [comment] 2019-06-25 03:32
Yes I can!

1. Clone git@github.com:zackbloom/afs.git
2. Run `npm install`
3. Run `wrangler preview`

**Comment by EverlastingBugstopper** [comment] 2019-06-25 15:41
Thanks @zackbloom 

The issue here is that your webpack configuration specifies the output path to be the root directory. I haven't dug into the source yet, but if you change your `webpack.config.js` to build your worker in a `dist` directory, it won't delete everything. My guess is that when wrangler builds for the preview, it builds the worker and then just deletes the directory that the built javascript is in without checking what directory that is.

While we work on a fix, I'd recommend replacing your webpack config with the contents below

```
const path = require('path');

module.exports = {
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, "dist"),
    filename: 'index.js'
  },
  module: {
    rules: [
      {
        test: /\.css$/i,
        use: 'raw-loader',
      },
    ],
  },
};

```

**Comment by EverlastingBugstopper** [comment] 2019-06-25 16:32
@sevki Could you take a look at how we want to fix this? I'm happy to tackle a fix, I'm just not quite sure what approach we want to take here. I've confirmed that this is the issue. Wranglerjs is returning `fullConfig.output.path` which happens to be the development directory when the webpack configuration doesn't create a child directory.

**Comment by zackbloom** [comment] 2019-06-25 17:31
As a user of Wrangler, I wasn't really exposed to webpack being used internally. I didn't think my webpack config would influence it's behavior at all, I just assumed I should put my output file at the location it expected.

**Comment by EverlastingBugstopper** [comment] 2019-06-25 18:27
@zackbloom that's a good point, we should make it clearer in the docs that wrangler uses `webpack.config.js` to build your script if the `type` field in `wrangler.toml` is specified. That being said, we shouldn't change the behavior as we still want to allow custom webpack builds with wrangler projects. 

It does seem like the default wrangler webpack template doesn't create a webpack.config file, and you would need to create your own if you wanted to do anything requiring a specific loader for things like es6 modules. We'll likely need to discuss what the right path is here before moving forward on a fix.

**Comment by xtuc** [comment] 2019-06-26 09:26
That's already a bug tracked here https://github.com/cloudflare/wrangler/issues/206. I think we can close this issue.

**Comment by EverlastingBugstopper** [comment] 2019-06-26 14:12
Hm, this seems like a separate bug. While wrangler generates a `./worker` directory for its own build, this particular case uses a preexisting `webpack.config.js` that causes the entire development directory to be deleted, not just `./worker`

I think this issue points to a broader problem with how wrangler handles webpack builds. We allow custom webpack config files, but in our generated projects we do not expose the webpack configuration used to build their project. I think the correct way to do this is to create a sensible default webpack config that the user can then modify/replace. This would eliminate the need to do any cleanup at all, we could leave the build artifacts where they are. This would also allow users to interact with tools like cloudworker.

**Comment by xtuc** [comment] 2019-06-26 14:18
Got you, that's right.

> This would eliminate the need to do any cleanup at all, we could leave the build artifacts where they are. This would also allow users to interact with tools like cloudworker
We cleaned webpack artifacts, not the worker ones. I doubt cloudworker will be able to take advatange of webpack output, however the watching might.

I think the right solution is to implement #116 so that no webpack dist is only visible for the watch mode. It related to #206 because the worker output should be configurable, it's persistent already.

**Comment by EverlastingBugstopper** [comment] 2019-06-26 14:28
Ooh, we _don't_ clean the build artifact, got it. Is there any reason we don't just use the `output` specified in `webpack.config.js` to store the build artifiacts rather than creating a separate directory? I don't think we should ask the user to configure the directory twice, and using webpack is something JavaScript devs are already familiar with. This would also (I think) eliminate the need to clean the webpack artifact. If we just used the webpack artifact itself rather than taking it and putting it in our own directory structure we wouldn't need to clean it. Does this sound right? I'm not entirely sure I understand everything going into the underlying architecture.

**Comment by granjef3** [comment] 2019-06-26 19:20
Some solutions I've thought of:

- don't populate `dist_to_clean` if the user webpack configuration provided an output folder. This implies the output folder is important as they didn't want to use the default.

- replace `dist_to_clean` with `files_to_clean`, an array of filenames that are the webpack output asset files (we can get this from `stats.assets` in `wranglerjs`) and delete those individually rather than an entire directory.

- override any configured output folder in `wranglerjs/index.js` to use a folder inside the wrangler build directory (currently `./worker`).

**Comment by xtuc** [comment] 2019-06-27 09:09
I would suggest doing an RFC for this issue and #206.

**Closed** 2019-07-15 09:33 UTC
Labels: bug, status - PR attached, subject - webpack, user report
