### ISSUE TITLE
Reported bundle size is different from real file size

### ISSUE THREAD

**Issue by PierBover** [cloudflare/wrangler#1227] opened 2020-04-28 20:24 UTC
### 🐛 Bug Report

So I created this repro to produce a bundle using `wrangler` and a bundle with a custom webpack config with similar params.

https://github.com/PierBover/cloudflare-workers-webpack-repo

As you can see the size of both bundles is exactly the same:

* [`worker.js`](https://github.com/PierBover/cloudflare-workers-webpack-repo/blob/master/dist/worker.js) produced by wrangler 2.83kB
* [`bundle.js`](https://github.com/PierBover/cloudflare-workers-webpack-repo/blob/master/dist/bundle.js) produced by a webpack custom config is 2.83kB

But when using wrangler the CLI reports this:

> ✨  Built successfully, built project size is 1 KiB.

Is the report wrong or is wrangler doing some extra compression?

Can we expect this extra compression when using a custom webpack config?

**Comment by xtuc** [comment] 2020-04-28 20:25
wrangler reports the compressed size because the 1Mb limit is based on that.

**Comment by PierBover** [comment] 2020-04-28 20:30
Can we expect this extra compression when using a custom webpack config?

What compression is being used?

**Comment by EverlastingBugstopper** [comment] 2020-05-14 20:55
Hey @PierBover - yes, this compression happens on all uploads by the API itself, and the bundle is gzipped

**Comment by EverlastingBugstopper** [comment] 2020-05-14 20:56
i'm gonna close this as a duplicate of #1188

**Closed by EverlastingBugstopper** 2020-05-14 20:56 UTC
Labels: user report
