### ISSUE TITLE
Native darwin/arm64 build via NPM

### ISSUE THREAD

**Issue by theashguy** [cloudflare/wrangler#1685] opened 2020-12-16 06:31 UTC
#### Overview and problem statement

About to pick up Cloudflare / Wrangler as a core platform for a new project and just replaced my daily machine with a new M1 mac. Noticed that the npm install instructions don't work with the new platform.

When I try to install it I get `Error: Unsupported platform: Darwin arm64`. 

#### Basic example

Just do the old `npm install wrangler-cli -g`

#### Workaround

Works fine if you use cargo to build directly for the env. Just make sure you remove the one installed by npm else you might get a clash of binaries :). It might be worth updating the documentation somewhere to point to this for the time being :).

**Comment by tillkruss** [comment] 2020-12-17 18:42
Just tried to install wrangler using NPM on an M1 machine and got the same error.

[Manual install](https://developers.cloudflare.com/workers/cli-wrangler/install-update#manual-install) doesn't work either.

**Comment by cpauwels** [comment] 2020-12-31 08:39
Same issue here, with wrangler being one of the only things holding me back to working 100% with my M1 Mac.

I installed rust via arm64 homebrew, and then used cargo to install wrangler. Everything compiled successfully, but when trying to run wrangler I get the following error:

```
  throw new Error(`Unsupported platform: ${type} ${arch}`);
  ^

Error: Unsupported platform: Darwin arm64
    at getPlatform (/Users/capauwels/.nvm/versions/node/v15.3.0/lib/node_modules/@cloudflare/wrangler/binary.js:19:9)
    at getBinary (/Users/capauwels/.nvm/versions/node/v15.3.0/lib/node_modules/@cloudflare/wrangler/binary.js:30:20)
    at run (/Users/capauwels/.nvm/versions/node/v15.3.0/lib/node_modules/@cloudflare/wrangler/binary.js:38:18)
    at Object.<anonymous> (/Users/capauwels/.nvm/versions/node/v15.3.0/lib/node_modules/@cloudflare/wrangler/run-wrangler.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

Any idea on when there will be support for M1 macs?

**Comment by xtuc** [comment] 2020-12-31 10:23
We don't have plans to work on M1 compatibility. However I think that's something wrangler needs to support.
The build configuration is here https://github.com/cloudflare/wrangler/blob/master/.github/workflows/release.yml#L71. Do you know if GitHub actions run M1 macs?

**Comment by tillkruss** [comment] 2020-12-31 15:58
They do not. We rented an M1 at MacStadium for testing. Cross-compiling works from Intel => ARM.

**Comment by xtuc** [comment] 2020-12-31 17:18
cross-compiling will probably work but i would be concerned that we can't run any unit tests for it.

**Comment by yongfook** [comment] 2021-01-22 01:27
@cpauwels looks like you need to remove the non-functioning npm version so the system can use the cargo binary.

Try running 

`npm uninstall -g @cloudflare/wrangler`

And then try the wrangler command again.

**Comment by theashguy** [comment] 2021-01-22 03:43
Can confirm that Cargo version does work-- sorry, should have come back to report on this. That said there are a range of other problems that you need to workaround. Ultimately I'm now using a custom webpack config to actually do the build and just using wrangler for deploys. 

So *yes* you can dev CFF on an M1, but wrangler is not M1 ready (actually one of the few things I've found that isn't), so be ready to fiddle with things.

**Comment by nilslice** [comment] 2021-02-08 22:11
I've seen a similar issue: 

```
wrangler publish    
⬇️   Installing wasm-pack v0.9.1...
Error: could not download `wasm-pack`
no prebuilt wasm-pack binaries are available for this platform
```

Which could potentially be that `wrangler` is a bit overeager in its convenience-added approach. Rather than expect to download a pre-built binary and fail otherwise, it could first check for an existing binary on the system, and fall back to attempting to download. Or, if `cargo` is installed, `cargo install <wasm-pack|generate|etc>` could be invoked to build these utils from source.

I've manually installed `wasm-pack`, `cargo-generate` and at least one other tool that doesn't have native pre-built binaries for M1 devices. So it should be fine, if not a little bit less "controlled", to first check for the binary before attempting to download one.

**Comment by nilslice** [comment] 2021-02-09 18:56
in-progress PR to address part of this issue: https://github.com/cloudflare/wrangler/pull/1763

**Comment by paulosouzainfo** [comment] 2021-02-24 13:21
in my case was install using **homebrew** with success! 
_brew install cloudflare-wrangler_

**Comment by yongfook** [comment] 2021-02-25 01:54
> in my case was install using **homebrew** with success!
> _brew install cloudflare-wrangler_

Installing cloudflare-wrangler is not a problem for me.

But it fails when attempting to run subsequent commands that depend on cargo-generate.

```
wrangler generate my-worker                 
⬇️ Installing cargo-generate v0.5.0...
Error: could not download `cargo-generate`
no prebuilt cargo-generate binaries are available for this platform
```

**Comment by bouk** [comment] 2021-02-27 10:17
You could release a universal binary, which contains both the arm64 and x86_64 compilations inside of it. To make one of those, you should do something like this:

```bash
$ rustup target add x86_64-apple-darwin aarch64-apple-darwin
$ cargo build --release --target=x86_64-apple-darwin
$ cargo build --release --target=aarch64-apple-darwin
$ lipo target/{x86_64,aarch64}-apple-darwin/release/wrangler -create -output wrangler
```

You then end up with a universal binary `wrangler` that'll natively run on either platform.

For those of you that have an M1 MacBook right now (like me) you can do this to install the x86_64 version and get working (assuming you have [rustup](https://rustup.rs) installed):

```bash
$ rustup target add x86_64-apple-darwin
$ cargo install wrangler --target=x86_64-apple-darwin
```

This will build and install the Intel version of `wrangler` and it should work fine.

**Comment by chengluyu** [comment] 2021-03-06 11:22
Currently I’m using my customized build. I replaced the `binary_path` in this line with the path to cargo on my machine. https://github.com/cloudflare/wrangler/blob/9f63cd067c3fd7327278538910e1e6dd5ee65e4e/src/commands/generate.rs#L50
Then I built the project and it works like a charm. Of course, this is a little bit hack. But if you're in an awkward situation like me where M1 is the only accessible machine, this may help.

**Comment by YUX** [comment] 2021-03-18 10:01
> I replaced the `binary_path` in this line with the path to cargo on my machine.

hi, what is that mean exactly? `let binary_path = "/Users/yux/.cargo/bin";` ?

**Comment by YUX** [comment] 2021-03-18 10:15
i've figured it out. `let binary_path = PathBuf::from(r"/opt/homebrew/bin/cargo");` works

thanks! @chengluyu

**Comment by paulosouzainfo** [comment] 2021-03-23 15:20
> > in my case was install using **homebrew** with success!
> > _brew install cloudflare-wrangler_
> 
> Installing cloudflare-wrangler is not a problem for me.
> 
> But it fails when attempting to run subsequent commands that depend on cargo-generate.
> 
> ```
> wrangler generate my-worker                 
> ⬇️ Installing cargo-generate v0.5.0...
> Error: could not download `cargo-generate`
> no prebuilt cargo-generate binaries are available for this platform
> ```

now, i receive the same error and i can't solve

**Comment by paulosouzainfo** [comment] 2021-03-23 15:27
> You could release a universal binary, which contains both the arm64 and x86_64 compilations inside of it. To make one of those, you should do something like this:
> 
> ```shell
> $ rustup target add x86_64-apple-darwin aarch64-apple-darwin
> $ cargo build --release --target=x86_64-apple-darwin
> $ cargo build --release --target=aarch64-apple-darwin
> $ lipo target/{x86_64,aarch64}-apple-darwin/release/wrangler -create -output wrangler
> ```
> 
> You then end up with a universal binary `wrangler` that'll natively run on either platform.
> 
> For those of you that have an M1 MacBook right now (like me) you can do this to install the x86_64 version and get working (assuming you have [rustup](https://rustup.rs) installed):
> 
> ```shell
> $ rustup target add x86_64-apple-darwin
> $ cargo install wrangler --target=x86_64-apple-darwin
> ```
> 
> This will build and install the Intel version of `wrangler` and it should work fine.

perfect solution. tks a lot, dude!

**Comment by leeanson19** [comment] 2021-04-25 15:19
> You could release a universal binary, which contains both the arm64 and x86_64 compilations inside of it. To make one of those, you should do something like this:
> 
> ```shell
> $ rustup target add x86_64-apple-darwin aarch64-apple-darwin
> $ cargo build --release --target=x86_64-apple-darwin
> $ cargo build --release --target=aarch64-apple-darwin
> $ lipo target/{x86_64,aarch64}-apple-darwin/release/wrangler -create -output wrangler
> ```
> 
> You then end up with a universal binary `wrangler` that'll natively run on either platform.
> 
> For those of you that have an M1 MacBook right now (like me) you can do this to install the x86_64 version and get working (assuming you have [rustup](https://rustup.rs) installed):
> 
> ```shell
> $ rustup target add x86_64-apple-darwin
> $ cargo install wrangler --target=x86_64-apple-darwin
> ```
> 
> This will build and install the Intel version of `wrangler` and it should work fine.

This works for me. Thanks!

**Comment by nilslice** [comment] 2021-04-27 15:43
This should be fixed in the latest release. Please give it a try and let us know if you still are hitting any errors:

`npm i -g @cloudflare/wrangler@1.16.1` or `cargo install wrangler --version 1.16.1`

**Closed by nilslice** 2021-04-27 15:43 UTC
Labels: feature, onboarding

**Comment by mrbm** [comment] 2021-04-27 18:13
https://github.com/cloudflare/wrangler/issues/1865

Posted errors on this thread

**Comment by yongfook** [comment] 2021-04-27 23:23
> This should be fixed in the latest release. Please give it a try and let us know if you still are hitting any errors:
> 
> `npm i -g @cloudflare/wrangler@1.16.1` or `cargo install wrangler --version 1.16.1`

Confirmed. This fixes the issue for me. Just generated my first worker on an M1 Macbook Air.

Thank you!

**Comment by yerofey** [comment] 2021-09-08 12:47
> Error: Unsupported platform: Darwin arm64

Create a Terminal\iTerm app Rosetta version: right click & "Get Info", check "Open in Rosetta". Now install homebrew how you would on an Intel Mac and everything will work.

<img width="157" alt="Снимок экрана 2021-09-08 в 15 47 23" src="https://user-images.githubusercontent.com/1276038/132511868-78356a2f-57ce-40b2-8c38-05d9cb11da08.png">
