### ISSUE TITLE
cargo failed to compile wrangler

### ISSUE THREAD

**Issue by junyussh** [cloudflare/wrangler#1759] opened 2021-02-06 08:21 UTC
#### Environment

* operating system: Arch Linux
* output of `rustc -V`: `rustc 1.51.0-nightly (04caa632d 2021-01-30)`
* output of `node -v`:
* output of `wrangler -V`:
* contents of `wrangler.toml`

#### Steps to reproduce

I run this command to install wrangler.

```bash
cargo install wrangler
```

And it throw errors:

```bash
error: internal compiler error: failed to process buffered lint here
   --> src/tail/session.rs:205:19
    |
205 |         Err(e) => failure::bail!(http::format_error(e, Some(&tail_help))),
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: failed to process buffered lint here
   --> src/tail/session.rs:118:17
    |
118 |                 failure::bail!(http::format_error(e, Some(&tail_help)))
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: failed to process buffered lint here
  --> src/tail/tunnel.rs:54:13
   |
54 | ...   failure::bail!("failed to kill cloudflared: {}\ncloudflared will eventually exit, or you can explicitly kill it by running `kill {}`", e, pid)
   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
   = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: failed to process buffered lint here
   --> src/tail/session.rs:187:5
    |
187 |     failure::bail!("Could not extract tunnel url from cloudflared")
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (04caa632d 2021-01-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `wrangler`
```

**Comment by ObsidianMinor** [comment] 2021-02-07 04:46
This is an internal compiler error caused by rust-lang/rust#81531.

**Comment by junyussh** [comment] 2021-02-08 06:10
So I have to wait rust to release a newer version to fix this problem?

**Comment by ObsidianMinor** [comment] 2021-02-08 06:26
It may already be fixed. Try updating your nightly compiler.

**Comment by junyussh** [comment] 2021-02-08 06:52
I've updated the nightly compiler, and I found my compiler is already the latest nightly version, which this issue used. Maybe Rust hasn't released a new version containing this PR right now.

**Comment by ObsidianMinor** [comment] 2021-02-08 07:14
If you want to install wrangler and force use stable cargo, you can use
```
cargo +stable install wrangler
```

**Comment by ObsidianMinor** [comment] 2021-02-12 03:22
I'm going to close this issue since it's an issue with rustc nightly, not with wrangler.

**Closed by ObsidianMinor** 2021-02-12 03:22 UTC
Labels: user report
