### ISSUE TITLE
thread '<unnamed>' panicked at 'Client::new()

### ISSUE THREAD

**Issue by RobertoSpaghetti** [cloudflare/wrangler#1674] opened 2020-12-10 08:29 UTC
### 🐛 Bug Report

Just installed Wrangler with:
npm install -g @cloudflare/wrangler

First command used: 
wrangler --version
returns:
wrangler 1.12.2
thread '<unnamed>' panicked at 'Client::new(): reqwest::Error { kind: Builder, source: Normal(ErrorStack([])) }', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.8/src/blocking/client.rs:575:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

#### Environment
* operating system: Debian 10 (up to date)
* output of `rustc -V`: command not found - installed it, then: rustc 1.41.1 (wrangler error unchanged)
* output of `node -v`: v12.10.0
* output of `wrangler -V`: see above
* contents of `wrangler.toml` none yet

#### Steps to reproduce

repeating 'wrangler --version' gives same error message.

#### What did you expect to see?
wrangler 1.12.2

#### What did you see instead?
wrangler 1.12.2
thread '<unnamed>' panicked at 'Client::new(): reqwest::Error { kind: Builder, source: Normal(ErrorStack([])) }', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.8/src/blocking/client.rs:575:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by RobertoSpaghetti** [comment] 2020-12-10 08:35
After continuing the getting started doc with:
wrangler generate my-worker
(completed without any error messages)
the problem seems to be solved:
wranger --version 
👷 ✨  wrangler 1.12.2

(No more error messages)

**Comment by xortive** [comment] 2021-02-24 22:24
closing as dupe of #1743, more info in that thread

**Closed by xortive** 2021-02-24 22:24 UTC
