### ISSUE TITLE
wrangler dev: panicked at 'Failed to connect to devtools instance'

### ISSUE THREAD

**Issue by JakubKoralewski** [cloudflare/wrangler#1510] opened 2020-08-19 18:12 UTC
#### Environment

* operating system: Microsoft Windows [Version 10.0.18363.1016]
* output of `rustc -V`: rustc 1.44.1 (c7087fe00 2020-06-17)
* output of `node -v`: v14.5.0
* output of `wrangler -V`: wrangler 1.10.3
* contents of `wrangler.toml`

```toml
name = "name-dev"
type = "webpack"
webpack_config = "webpack.dev.js"
account_id = "id ahsjkdhalsdhalkjdh"
workers_dev = true
route = ""
zone_id = ""

[env.production]
name = "name"
webpack_config = "webpack.config.js"
```

#### Steps to reproduce

If I leave `wrangler dev` running for a long time sometimes this happens. It is unclear for me why. It may be my unstable internet connection, but still if so, I'd expect for wrangler to keep retrying until the connection is restored or something like that for a more graceful experience.

#### What did you see instead?

message 'Nieznany host' means 'unknown host'

```
thread 'tokio-runtime-worker' panicked at 'Failed to connect to devtools instance: Io(Os { code: 11001, kind: Other, message: "Nieznany host." })', C:\Users\Admin\.cargo\registry\src\github.com-1ecc6299db9ec823\wrangler-1.10.3\src\commands\dev\socket.rs:29:30
stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace/dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src\libstd\sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src\libstd\sys_common/backtrace.rs:59
   4: core::fmt::write
             at src\libcore\fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src\libstd\io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src\libstd\sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src\libstd\sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src\libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src\libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:511
  11: rust_begin_unwind
             at src\libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src\libcore/panicking.rs:111
  13: core::option::expect_none_failed
             at src\libcore/option.rs:1268
  14: wrangler::commands::dev::socket::listen::{{closure}}
  15: tokio::runtime::task::core::Core<T,S>::poll
  16: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  17: tokio::runtime::task::harness::Harness<T,S>::poll
  18: std::thread::local::LocalKey<T>::with
  19: tokio::runtime::thread_pool::worker::Context::run_task
  20: tokio::runtime::thread_pool::worker::Context::run
  21: tokio::macros::scoped_tls::ScopedKey<T>::set
  22: tokio::runtime::thread_pool::worker::run
  23: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  24: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  25: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  26: tokio::runtime::task::harness::Harness<T,S>::poll
  27: tokio::runtime::blocking::pool::Inner::run
  28: tokio::runtime::context::enter
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Error: panic
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new_unresolved
   2: failure::backtrace::internal::InternalBacktrace::new
   3: <failure::backtrace::Backtrace as core::default::Default>::default
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: <tokio::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll
   6: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: std::thread::local::LocalKey<T>::with
   9: tokio::runtime::enter::Enter::block_on
  10: tokio::runtime::context::enter
  11: wrangler::commands::dev::gcs::dev
  12: wrangler::commands::dev::dev
  13: wrangler::run
  14: wrangler::main
  15: std::rt::lang_start::{{closure}}
  16: std::rt::lang_start_internal::{{closure}}
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd/rt.rs:52
      std::panicking::try::do_call
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd/panicking.rs:331
      std::panicking::try
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd/panicking.rs:274
      std::panic::catch_unwind
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd/panic.rs:394
      std::rt::lang_start_internal
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd/rt.rs:51
  17: main
  18: __tmainCRTStartup
  19: mainCRTStartup
  20: <unknown>
  21: <unknown>
```

With `FULL` backtrace, this is right after starting the command, and my internet connection seemed fine.
```
 Built successfully, built project size is 47 KiB.
 Listening on http://127.0.0.1:8787
 Detected changes...
 Ignoring stale first change
thread 'tokio-runtime-worker' panicked at 'Failed to connect to devtools instance: Io(Os { code: 11001, kind: Other, message: "Nieznany host." })', C:\Users\Admin\.cargo\registry\src\github.com-1ecc6299db9ec823\wrangler-1.10.3\src\commands\dev\socket.rs:29:30
stack backtrace:
   0:           0xf9f09b - backtrace::backtrace::dbghelp::trace::h39d3b7e54c98bfeb
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace/dbghelp.rs:88
   1:           0xf9f09b - backtrace::backtrace::trace_unsynchronized::hece815955ee584f5
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace/mod.rs:66
   2:           0xf9f09b - std::sys_common::backtrace::_print_fmt::h6329aad3c4e33b91
                               at src\libstd\sys_common/backtrace.rs:78
   3:           0xf9f09b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h70d081ab68653703
                               at src\libstd\sys_common/backtrace.rs:59
   4:           0xfcb16b - core::fmt::write::h8208faec44da3f47
                               at src\libcore\fmt/mod.rs:1069
   5:           0xf8fde5 - std::io::Write::write_fmt::hf1bea4fcea6e8faf
                               at src\libstd\io/mod.rs:1504
   6:           0xfa38e1 - std::sys_common::backtrace::_print::h8d3665e9fac8ab4d
                               at src\libstd\sys_common/backtrace.rs:62
   7:           0xfa38e1 - std::sys_common::backtrace::print::h2c7cda1ee814fd49
                               at src\libstd\sys_common/backtrace.rs:49
   8:           0xfa38e1 - std::panicking::default_hook::{{closure}}::h539aa264476ab506
                               at src\libstd/panicking.rs:198
   9:           0xfa3556 - std::panicking::default_hook::h375187d8fe0b473b
                               at src\libstd/panicking.rs:218
  10:           0xfa3f54 - std::panicking::rust_panic_with_hook::h9fee4158d03ea72d
                               at src\libstd/panicking.rs:511
  11:           0xfa3b74 - rust_begin_unwind
                               at src\libstd/panicking.rs:419
  12:           0xfc7bc0 - core::panicking::panic_fmt::hf5f4b1ece6e49331
                               at src\libcore/panicking.rs:111
  13:           0xfc7823 - core::option::expect_none_failed::h75bc420e8ab0df51
                               at src\libcore/option.rs:1268
  14:           0x4ccf76 - wrangler::commands::dev::socket::listen::{{closure}}::hfdf2ad3c55940ba5
  15:           0x5af13a - tokio::runtime::task::core::Core<T,S>::poll::h1ebd5ece289a12d4
  16:           0x43a81c - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hc58bb649371093d8
  17:           0x77ad3c - tokio::runtime::task::harness::Harness<T,S>::poll::h668016d271f88332
  18:           0xe3c1c6 - std::thread::local::LocalKey<T>::with::h952b3184d8beb16a
  19:           0xe5cabe - tokio::runtime::thread_pool::worker::Context::run_task::h1bbbedc55b655e66
  20:           0xe5bd97 - tokio::runtime::thread_pool::worker::Context::run::h2aa2d45d9121b377
  21:           0xe5f1d1 - tokio::macros::scoped_tls::ScopedKey<T>::set::hafb773f2a9153810
  22:           0xe5bbda - tokio::runtime::thread_pool::worker::run::h10946eaecda27a65
  23:           0xe80998 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::hf8173ffeea7d33a2
  24:           0xe60dce - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h3c4ca295d265cc4b
  25:           0xe8866f - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h47d01caa69d0d9e0
  26:           0xe6c130 - tokio::runtime::task::harness::Harness<T,S>::poll::h63b08ffdd2f5e92a
  27:           0xe545e6 - tokio::runtime::blocking::pool::Inner::run::h55a8ac38df4dce14
  28:           0xe7bc8c - tokio::runtime::context::enter::h2512afe60ecb13d3
  29:           0xe648e4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h940f9c82de61e060
  30:           0xe51d52 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hdac0371e2a282b0b
  31:           0xfb2920 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h128ecbf3019fe93f
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\src\liballoc/boxed.rs:1008
  32:           0xfb2920 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h51262c82125a675c
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\src\liballoc/boxed.rs:1008
  33:           0xfb2920 - std::sys::windows::thread::Thread::new::thread_start::ha62450f1da1b59c3
                               at src\libstd\sys\windows/thread.rs:56
  34:     0x7ffd6df47bd4 - _report_error
  35:     0x7ffd6ea0ce51 - _report_error
Error: panic
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new_unresolved
   2: failure::backtrace::internal::InternalBacktrace::new
   3: <failure::backtrace::Backtrace as core::default::Default>::default
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: <tokio::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll
   6: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: std::thread::local::LocalKey<T>::with
   9: tokio::runtime::enter::Enter::block_on
  10: tokio::runtime::context::enter
  11: wrangler::commands::dev::gcs::dev
  12: wrangler::commands::dev::dev
  13: wrangler::run
  14: wrangler::main
  15: std::rt::lang_start::{{closure}}
  16: std::rt::lang_start_internal::{{closure}}
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd/rt.rs:52
      std::panicking::try::do_call
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd/panicking.rs:331
      std::panicking::try
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd/panicking.rs:274
      std::panic::catch_unwind
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd/panic.rs:394
      std::rt::lang_start_internal
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd/rt.rs:51
  17: main
  18: __tmainCRTStartup
  19: mainCRTStartup
  20: <unknown>
  21: <unknown>
````

Another one:
```
Detected changes...
 Built successfully, built project size is 58 KiB.
 Detected changes...
 Built successfully, built project size is 58 KiB.
thread '<unnamed>' panicked at '--watch change message failed to send: "SendError(..)"', C:\Users\Admin\.cargo\registry\src\github.com-1ecc6299db9ec823\wrangler-1.10.3\src\wranglerjs\mod.rs:110:29
stack backtrace:
   0:           0xf9f09b - backtrace::backtrace::dbghelp::trace::h39d3b7e54c98bfeb
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace/dbghelp.rs:88
   1:           0xf9f09b - backtrace::backtrace::trace_unsynchronized::hece815955ee584f5
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace/mod.rs:66
   2:           0xf9f09b - std::sys_common::backtrace::_print_fmt::h6329aad3c4e33b91
                               at src\libstd\sys_common/backtrace.rs:78
   3:           0xf9f09b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h70d081ab68653703
                               at src\libstd\sys_common/backtrace.rs:59
   4:           0xfcb16b - core::fmt::write::h8208faec44da3f47
                               at src\libcore\fmt/mod.rs:1069
   5:           0xf8fde5 - std::io::Write::write_fmt::hf1bea4fcea6e8faf
                               at src\libstd\io/mod.rs:1504
   6:           0xfa38e1 - std::sys_common::backtrace::_print::h8d3665e9fac8ab4d
                               at src\libstd\sys_common/backtrace.rs:62
   7:           0xfa38e1 - std::sys_common::backtrace::print::h2c7cda1ee814fd49
                               at src\libstd\sys_common/backtrace.rs:49
   8:           0xfa38e1 - std::panicking::default_hook::{{closure}}::h539aa264476ab506
                               at src\libstd/panicking.rs:198
   9:           0xfa3556 - std::panicking::default_hook::h375187d8fe0b473b
                               at src\libstd/panicking.rs:218
  10:           0xfa3f54 - std::panicking::rust_panic_with_hook::h9fee4158d03ea72d
                               at src\libstd/panicking.rs:511
  11:           0xfa3b74 - rust_begin_unwind
                               at src\libstd/panicking.rs:419
  12:           0xfc7bc0 - core::panicking::panic_fmt::hf5f4b1ece6e49331
                               at src\libcore/panicking.rs:111
  13:           0xfc7823 - core::option::expect_none_failed::h75bc420e8ab0df51
                               at src\libcore/option.rs:1268
  14:           0x617c4c - std::sys_common::backtrace::__rust_begin_short_backtrace::h4c30eabb8237050e
  15:           0x50d619 - core::ops::function::FnOnce::call_once{{vtable.shim}}::ha6359e7970c9708a
  16:           0xfb2920 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h128ecbf3019fe93f
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\src\liballoc/boxed.rs:1008
  17:           0xfb2920 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h51262c82125a675c
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\src\liballoc/boxed.rs:1008
  18:           0xfb2920 - std::sys::windows::thread::Thread::new::thread_start::ha62450f1da1b59c3
                               at src\libstd\sys\windows/thread.rs:56
  19:     0x7ffd6df47bd4 - _report_error
  20:     0x7ffd6ea0ce51 - _report_error
thread 'tokio-runtime-worker' panicked at 'Failed to connect to devtools instance: Io(Os { code: 11001, kind: Other, message: "Nieznany host." })', C:\Users\Admin\.cargo\registry\src\github.com-1ecc6299db9ec823\wrangler-1.10.3\src\commands\dev\socket.rs:29:30
stack backtrace:
   0:           0xf9f09b - backtrace::backtrace::dbghelp::trace::h39d3b7e54c98bfeb
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace/dbghelp.rs:88
   1:           0xf9f09b - backtrace::backtrace::trace_unsynchronized::hece815955ee584f5
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace/mod.rs:66
   2:           0xf9f09b - std::sys_common::backtrace::_print_fmt::h6329aad3c4e33b91
                               at src\libstd\sys_common/backtrace.rs:78
   3:           0xf9f09b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h70d081ab68653703
                               at src\libstd\sys_common/backtrace.rs:59
   4:           0xfcb16b - core::fmt::write::h8208faec44da3f47
                               at src\libcore\fmt/mod.rs:1069
   5:           0xf8fde5 - std::io::Write::write_fmt::hf1bea4fcea6e8faf
                               at src\libstd\io/mod.rs:1504
   6:           0xfa38e1 - std::sys_common::backtrace::_print::h8d3665e9fac8ab4d
                               at src\libstd\sys_common/backtrace.rs:62
   7:           0xfa38e1 - std::sys_common::backtrace::print::h2c7cda1ee814fd49
                               at src\libstd\sys_common/backtrace.rs:49
   8:           0xfa38e1 - std::panicking::default_hook::{{closure}}::h539aa264476ab506
                               at src\libstd/panicking.rs:198
   9:           0xfa3556 - std::panicking::default_hook::h375187d8fe0b473b
                               at src\libstd/panicking.rs:218
  10:           0xfa3f54 - std::panicking::rust_panic_with_hook::h9fee4158d03ea72d
                               at src\libstd/panicking.rs:511
  11:           0xfa3b74 - rust_begin_unwind
                               at src\libstd/panicking.rs:419
  12:           0xfc7bc0 - core::panicking::panic_fmt::hf5f4b1ece6e49331
                               at src\libcore/panicking.rs:111
  13:           0xfc7823 - core::option::expect_none_failed::h75bc420e8ab0df51
                               at src\libcore/option.rs:1268
  14:           0x4ccf76 - wrangler::commands::dev::socket::listen::{{closure}}::hfdf2ad3c55940ba5
  15:           0x5af13a - tokio::runtime::task::core::Core<T,S>::poll::h1ebd5ece289a12d4
  16:           0x43a81c - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hc58bb649371093d8
  17:           0x77ad3c - tokio::runtime::task::harness::Harness<T,S>::poll::h668016d271f88332
  18:           0xe3c1c6 - std::thread::local::LocalKey<T>::with::h952b3184d8beb16a
  19:           0xe5cabe - tokio::runtime::thread_pool::worker::Context::run_task::h1bbbedc55b655e66
  20:           0xe5bd97 - tokio::runtime::thread_pool::worker::Context::run::h2aa2d45d9121b377
  21:           0xe5f1d1 - tokio::macros::scoped_tls::ScopedKey<T>::set::hafb773f2a9153810
  22:           0xe5bbda - tokio::runtime::thread_pool::worker::run::h10946eaecda27a65
  23:           0xe80998 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::hf8173ffeea7d33a2
  24:           0xe60dce - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h3c4ca295d265cc4b
  25:           0xe8866f - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h47d01caa69d0d9e0
  26:           0xe6c130 - tokio::runtime::task::harness::Harness<T,S>::poll::h63b08ffdd2f5e92a
  27:           0xe545e6 - tokio::runtime::blocking::pool::Inner::run::h55a8ac38df4dce14
  28:           0xe7bc8c - tokio::runtime::context::enter::h2512afe60ecb13d3
  29:           0xe648e4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h940f9c82de61e060
  30:           0xe51d52 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hdac0371e2a282b0b
  31:           0xfb2920 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h128ecbf3019fe93f
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\src\liballoc/boxed.rs:1008
  32:           0xfb2920 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h51262c82125a675c
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\src\liballoc/boxed.rs:1008
  33:           0xfb2920 - std::sys::windows::thread::Thread::new::thread_start::ha62450f1da1b59c3
                               at src\libstd\sys\windows/thread.rs:56
  34:     0x7ffd6df47bd4 - _report_error
  35:     0x7ffd6ea0ce51 - _report_error
Error: panic
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new_unresolved
   2: failure::backtrace::internal::InternalBacktrace::new
   3: <failure::backtrace::Backtrace as core::default::Default>::default
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: <tokio::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll
   6: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: std::thread::local::LocalKey<T>::with
   9: tokio::runtime::enter::Enter::block_on
  10: tokio::runtime::context::enter
  11: wrangler::commands::dev::gcs::dev
  12: wrangler::commands::dev::dev
  13: wrangler::run
  14: wrangler::main
  15: std::rt::lang_start::{{closure}}
  16: std::rt::lang_start_internal::{{closure}}
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd/rt.rs:52
      std::panicking::try::do_call
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd/panicking.rs:331
      std::panicking::try
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd/panicking.rs:274
      std::panic::catch_unwind
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd/panic.rs:394
      std::rt::lang_start_internal
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd/rt.rs:51
  17: main
  18: __tmainCRTStartup
  19: mainCRTStartup
  20: <unknown>
  21: <unknown>
```

**Comment by JakubKoralewski** [comment] 2020-08-27 10:01
This is now happening every minute. I have now observed my WiFi icon flicker into *no internet connection* icon in my Windows Taskbar right as the error happened. Adding some e2e tests with unstable internet connection would be a great first step in diagnosing the problem.

**Comment by dgitq** [comment] 2020-09-11 17:56
Yea I have this very often as well. Did not happen as much with old wrangler version: v1.10.x

**Comment by davidbarratt** [comment] 2020-10-11 18:48
I'm having this problem on Linux (Ubuntu) on 1.11.0, if I downgrade to 1.10.0 it works perfectly.

**Comment by tsndr** [comment] 2020-11-09 17:54
Same problem for me on macOS 10.15, this Issue is open since August, can't someone finally fix this? It's super annoying. 😩

**Comment by McSneaky** [comment] 2020-11-27 09:21
Same problem with different version and stack

**$ cat /etc/os-release**
```
NAME="openSUSE Tumbleweed"
VERSION_ID="20201119"
...
```
**$ wrangler --version**
```
👷 ✨  wrangler 1.12.2
```

```
thread 'tokio-runtime-worker' panicked at 'Failed to connect to devtools instance: Http(500)', src/commands/dev/socket.rs:28:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1221
   3: wrangler::commands::dev::socket::listen::{{closure}}
   4: tokio::runtime::task::core::Core<T,S>::poll
   5: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
   6: tokio::runtime::task::harness::Harness<T,S>::poll
   7: tokio::runtime::thread_pool::worker::Context::run_task
   8: tokio::runtime::thread_pool::worker::Context::run
   9: tokio::macros::scoped_tls::ScopedKey<T>::set
  10: tokio::runtime::thread_pool::worker::run
  11: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  12: tokio::runtime::task::core::Core<T,S>::poll
  13: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  14: tokio::runtime::task::harness::Harness<T,S>::poll
  15: tokio::runtime::blocking::pool::Inner::run
  16: tokio::runtime::context::enter
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Error: panic
   0: failure::backtrace::internal::InternalBacktrace::new
   1: <failure::backtrace::Backtrace as core::default::Default>::default
   2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   3: <tokio::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll
   4: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: std::thread::local::LocalKey<T>::with
   7: tokio::runtime::enter::Enter::block_on
   8: tokio::runtime::thread_pool::ThreadPool::block_on
   9: tokio::runtime::context::enter
  10: wrangler::commands::dev::gcs::dev
  11: wrangler::commands::dev::dev
  12: wrangler::run
  13: wrangler::main
  14: std::sys_common::backtrace::__rust_begin_short_backtrace
  15: std::rt::lang_start::{{closure}}
  16: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373:40
      std::panicking::try
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337:19
      std::panic::catch_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379:14
      std::rt::lang_start_internal
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/rt.rs:51:25
  17: main
```

**Comment by salarkhan** [comment] 2020-12-09 01:36
same issue: `macOS 10.15` / `wrangler 1.12.0` / `node v14.15.0`

**Comment by james090500** [comment] 2020-12-16 11:04
Exact same issues as above. `Windows 10 20H2` / `Wrangler 1.12.2` / `Node 12.18.4`.

There's no work around and we can't work like this...

**Comment by McSneaky** [comment] 2020-12-20 00:24
For me it worked to go back to 1.10.0 and restart it several times. With 1.10.0 it seemed to fail only every 4th run or so

**Comment by Alkalurops** [comment] 2021-01-01 16:48
I have this error on macOS Big Sur 11.1

**Comment by kateetrant** [comment] 2021-01-04 20:00
I have this error running `macOS Big Sur 11.1` / `wrangler 1.12.3` / node `14.15.4`

**Comment by aleclarson** [comment] 2021-01-05 23:01
`macOS 10.15.7` / `wrangler 1.12.3` / `node 14.15.3`

Downgrading to `1.10.3` fixed it for me

**Comment by ags799** [comment] 2021-01-15 17:27
Also getting this error, tried `v1.10.0`, `v1.10.3`, and `v1.11.0`.

I can work around it by:
1. Running `wrangler dev`.
2. Immediately, in a separate terminal, requesting the worker (`curl http://127.0.0.1`).

Does this work for anyone else?

**Comment by tojacob** [comment] 2021-01-21 00:59
@ags799 Yep. I've been doing that too. But it only works for a little while.

**Comment by ags799** [comment] 2021-02-03 22:00
[This will prevent the panics](https://github.com/cloudflare/wrangler/pull/1752).

**Comment by Alkalurops** [comment] 2021-02-23 21:40
Installed @cloudflare/wrangler@1.13.0, now getting this error every time:

```
[worker] thread 'tokio-runtime-worker' panicked at 'Failed to connect to devtools instance: Http(400)', src/commands/dev/socket.rs:29:14
[worker] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[worker] 👂  Listening on http://127.0.0.1:8787
[worker] Error: panic
```
Downgrading like @aleclarson did to 1.10.3 seems to work.

**Comment by Alkalurops** [comment] 2021-02-23 21:57
🤦 I think I switched  switched off WebSockets in the Network configuration panel. Once I switched it on everything immediately worked again (with the periodic panic later on…).

**Comment by merlinnot** [comment] 2021-02-24 15:21
>  I think I switched switched off WebSockets in the Network configuration panel. Once I switched it on everything immediately worked again (with the periodic panic later on…).

Oh, that's the reason? Lifesaver, thanks!

**Comment by lukevalenta** [comment] 2021-03-11 19:55
I ran into a similar issue when both `workers_dev` and `zone_id` are specified for the same deployment in `wranglers.toml`. I posted a workaround at https://github.com/cloudflare/wrangler/issues/1711 (which I believe is a duplicate of this issue?)

**Comment by quarties** [comment] 2021-07-09 23:03
same issue
`macOS 11.4` / `wrangler 1.17.0` (I also tried latest beta) / `node v14.17.0`

reverting to `1.10.X` fixes it, but I would like to avoid using legacy verions 😞 any news on this?

my `wranagler.toml`
```
# top level configuration
type = "javascript"
account_id = "xxx"
zone_id = "xxx"
usage_model = "bundled"
name = "woocommerce-product-cards-staging"
route = "woocommerce.staging.livechat.expert/*"
kv_namespaces = [
    { binding = "STORES", id = "xxx", preview_id = "xxx" },
]

[build]
command = "npm run build"
[build.upload]
format = "service-worker"

[dev]
ip = "127.0.0.1"
port = 8080
local_protocol="http"
upstream_protocol="https"

# environment configuration
[env.production]
workers_dev = true
name = "woocommerce-product-cards"
route = "woocommerce.livechat.expert/*"
kv_namespaces = [
    { binding = "STORES", id = "xxx" },
]
```

**Comment by seekingtheoptimal** [comment] 2022-02-02 18:31
I just wanted to rerun an older project of mine, and same happens for me when trying to run wrangler dev

**Comment by petebacondarwin** [comment] 2022-06-21 09:15
Please try running your Workers project with the latest Wrangler (`npm -g install wrangler@latest`). If you still get the problem please create a new issue at https://github.com/cloudflare/wrangler2/issues/new/choose.

**Closed by petebacondarwin** 2022-06-21 09:15 UTC
Labels: bug, dev
