### ISSUE TITLE
cargo-generate not being installed correctly

### ISSUE THREAD

**Issue by adamchalmers** [cloudflare/wrangler#324] opened 2019-07-16 15:14 UTC
**Problem:**
I was following the Quickstart and installed Wrangler via Cargo. Then I got an error when running `wrangler generate`. Unfortunately I didn't copy the error. However, I fixed it by running `cargo install cargo-generate`. I could then successfully run `wrangler generate`.

**Proposed solution:**
The quickstart guide should prompt users to `cargo install cargo-generate` if they're install Wrangler via Cargo.

**Comment by ashleymichal** [comment] 2019-07-16 15:50
should we prompt, or install on behalf of the user?

**Comment by EverlastingBugstopper** [comment] 2019-07-16 15:52
I’d say we should just install it. When I’m installing new tools I don’t really care what the dependencies are I Just Want It To Work.

**Comment by granjef3** [comment] 2019-07-16 15:59
This sounds like a `binary-install` problem as we already install on behalf of the user

**Comment by adamchalmers** [comment] 2019-07-16 22:11
@granjef3 If it's a bug in the install toolset, I probably shouldn't add an "install cargo-generate" step in the quickstart, right?

**Comment by granjef3** [comment] 2019-07-16 22:28
@adamchalmers exactly. Could you see if you get that error again if you uninstall `cargo-generate` and `wrangler` and give some more info on your platform/rust version?

**Comment by granjef3** [comment] 2019-07-24 21:10
Duplicate of https://github.com/cloudflare/wrangler/issues/35 after testing with Adam.

**Closed by granjef3** 2019-07-24 21:10 UTC
Labels: status - needs more info, status - needs repro, subject - cargo install, user report
