### ISSUE TITLE
renaming a project

### ISSUE THREAD

**Issue by rita3ko** [cloudflare/wrangler#774] opened 2019-10-09 22:23 UTC
#### Steps to reproduce
1. Create a new Worker using `wrangler generate`. Let's say it's named `my-worker`
2. Use `wrangler publish` to deploy the Worker
3. Change the `name` field in wrangler.toml to `worker`

#### What did you expect to see?
My Worker (in the UI for example) is not renamed from `my-worker` to `worker`

#### What did you see instead?
I now have two Workers: `my-worker` and `worker` (i.e. the old name is still there).

**Comment by ashleygwilliams** [comment] 2019-10-14 15:12
this is expected behavior. the wrangler.toml is the source of truth, if you rename the worker to a new name, the worker no longer knows the old workers name.

alternatively we could expose a command for renaming- which would delete the current worker, upload a new one, and update the wrangler.toml. would that work?

**Comment by xtuc** [comment] 2019-10-15 10:15
I think it's expected and I'm not a fan of a rename command because I doubt it's a common use case. That said, we could detect that multiple workers matches the exact same route.

**Comment by ashleymichal** [comment] 2019-10-15 14:37
come to think of it, this is another issue that would be addressed by implementing #330

**Comment by ashleymichal** [comment] 2019-12-06 19:42
i'm pretty sure the api actually has a rename endpoint... it was exposed during zoneless development.

**Comment by gabbifish** [comment] 2019-12-06 19:49
We are going to close this for now, given that the use cases for worker renaming seem limited. Having both the old name worker and new name worker present also acts as a "safety rail" of sorts against unexpected side effects from renaming a worker.

**Closed by gabbifish** 2019-12-06 19:49 UTC
Labels: category - feature, user report
