### ISSUE TITLE
Calling wrangler publish will remove KV bindings

### ISSUE THREAD

**Issue by davemurphysf** [cloudflare/wrangler#2301] opened 2022-09-03 17:06 UTC
#### Describe the bug

On wrangler 2.0.28 (and possibly 2.0.26), after I call `wrangler publish` without a wrangler.toml file, my KV bindings are removed from my worker.  My full publish command in case its relevant: `wrangler publish dist/index.mjs --name auth --tsconfig ./tsconfig.json --latest`

#### Reproduce the bug

1. `wrangler login`
2. `wrangler init wrangTest --yes`
3. `cd wrangTest && rm wrangler.toml`
4. `wrangler publish src/index.ts --name wrangtest --latest`
5. [Add KV binding to worker in dashboard.  Name and which KV namespace does not matter]
6. Run `wrangler publish src/index.ts --name wrangtest --latest` again
7. KV binding will be gone :-( 

#### Expected behavior

Existing KV binding should not be removed on `wrangler publish`

#### Environment and versions

Fill out the following information about your environment.

* operating system: MacOS Monterey 12.5.1
* output of `wrangler -V`:  ⛅️ wrangler 2.0.28
* output of `node -v`: v18.7.0
* content of `wrangler.toml`: no wrangler.toml

**Comment by Erisa** [comment] 2022-09-04 11:23
Hi!

Since you're using wrangler 2, it's best to raise this issue in the wrangler2 repository: https://github.com/cloudflare/wrangler2/issues

**Comment by rozenmd** [comment] 2022-09-12 14:45
Closing this as duplicate of https://github.com/cloudflare/wrangler2/issues/1771

**Closed by rozenmd** 2022-09-12 14:45 UTC
Labels: bug
