### ISSUE TITLE
URGENT install broken with 500 error downloading binary

### ISSUE THREAD

**Issue by samuelcolvin** [cloudflare/wrangler#1604] opened 2020-10-14 15:05 UTC
I'm trying to install wrangler on macos with `npm install -g @cloudflare/wrangler` and getting an error:

```
> node ./install-wrangler.js

Downloading release https://workers.cloudflare.com/get-npm-wrangler-binary/1.11.0/x86_64-apple-darwin
Error fetching release Request failed with status code 500
```

When I go to https://workers.cloudflare.com/get-npm-wrangler-binary/1.11.0/x86_64-apple-darwin I get an intermittent 500 error.

**Comment by rita3ko** [comment] 2020-10-14 15:11
Hi @samuelcolvin! Thanks for reporting this. Going to close it as a duplicate of #1587 which @nataliescottdavidson is currently looking into.

**Closed by rita3ko** 2020-10-14 15:11 UTC
Labels: user report
