### ISSUE TITLE
Character limit on `secret put` paste

### ISSUE THREAD

**Issue by lukeed** [cloudflare/wrangler#1975] opened 2021-06-28 17:11 UTC
#### Describe the bug

When trying to paste a plaintext blob, the `wrangler secret put NAME` interactive reader cuts off after 1K characters. 

```js
VALUE.length; //=> 1703
ACCEPTED.length //=> 1008
```

#### Reproduce the bug

```js
var stub = 'x'.repeat(1e3) + 'y'.repeat(1e3);
//=> "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"
```

```sh
$ wrangler secret put FOOBAR
#=> paste `stub`
```

I only see 24 `y` characters.

#### Expected behavior

It should have accepted the full string, since it's below the 5kB secret limit.

#### Environment and versions

* operating system: macOS 11.4
* output of `wrangler -V`: 1.17.0
* output of `node -v`: 14.15.3
* content of `wrangler.toml`: N/A

**Comment by nilslice** [comment] 2021-07-07 19:02
hey @lukeed - can you check that the output of your paste is the full secret / length you expect? 

i was able to get the full secret created by wrangler (using the 2000 chars in your example) all the way through the 5k limit. 

```sh
 node -e "console.log('x'.repeat(1e3) + 'y'.repeat(1e3));" | wrangler secret put LENGTH_CHECK
```

since it works by piping the exact result output, my guess is that somewhere before you paste the value in at the terminal. maybe even the terminal itself? if you can, lmk if the pipe option works for you.

**Comment by lukeed** [comment] 2021-07-07 19:09
Hey, not sure what the difference is. The cut-off still happens for me, just as it did before. Screenshot below, using the same `stub` from above:

<img width="886" alt="Screen Shot 2021-07-07 at 12 08 33 PM" src="https://user-images.githubusercontent.com/5855893/124815478-2eab7900-df1c-11eb-8ada-a8270a6c8e83.png">

**Comment by nilslice** [comment] 2021-07-07 19:50
ok, will need to look into it further as this can't be reliably reproduced on all platforms.

**Comment by nilslice** [comment] 2021-07-08 19:14
I believe this is a system limitation, and not to do with `wrangler` itself. On various platforms, configuration is set which in this case, limits the max size of an input line (e.g. the pasted string). On macos, this limit is set to 1024, which is what you observe. You can verify this by running: 

```python
#!/usr/bin/env python
from os import fpathconf
print(fpathconf(0, 'PC_MAX_CANON'))
```

There is some additional mention of this in the following documentation: 
https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/pathconf.2.html

I'm going to close this for now, leaving the recommendation to pipe any secret (larger than your system's max line length) into wrangler, instead of copy/pasting into the interactive terminal, as such (for a system with a bash-like shell): 

```bash
cat ./secret-file.txt | wrangler secret put MY_SECRET

# or from a paste buffer, e.g. on macos:
pbpaste | wrangler secret put MY_SECRET
```

**Closed by nilslice** 2021-07-08 19:14 UTC
Labels: bug, investigate
