### ISSUE TITLE
Webpack target=webworker prevents using some npm packages

### ISSUE THREAD

**Issue by MiroslavPetrik** [cloudflare/wrangler#781] opened 2019-10-12 15:50 UTC
### 🐛 Bug Report

After updating to v1.4.0 my app stopped working, because some packages are not processed by the webpack as they were previously due to the setting of `target` in the config.

The following line is problematic for me
https://github.com/cloudflare/wrangler/commit/e7416ffe4abff5a8b13b40619181f180edae8d1f#diff-6809655e3d30e1bf1bcacadfba926ecfR55

I want to use `node` environment in which webpack is able to process the `@hapi/joi` plugin in such way that it works in the worker. I verified this by bundling the `joi` with webpack locally and running the output via `node`. It doesn't work with the `webworker` target as `window` variable is used in the script, thus it's not isomorphic.

Potentially, the target can be troublesome for other packages.

#### Environment

* operating system:
* output of `rustc -V`: rustc 1.37.0 (eae3437df 2019-08-13)
* output of `node -v`: v10.15.3
* output of `wrangler -V`: 👷 ✨  wrangler 1.4.0

#### Steps to reproduce

1. install `@hapi/joi`
2. use some api in your worker script
```
import * as Joi from "@hapi/joi";

const schema = Joi.object({
    name: Joi.string().required(),
});
```
3. run the worker (`wrangler preview`)
4. it fails due to `window` not accessible

#### What did you expect to see?

The worker should work without error.

#### What did you see instead?

Worker fails to run, error is thrown:
```
ReferenceError: window is not defined
    at Object.<anonymous> 
```

**Comment by xtuc** [comment] 2019-10-13 16:53
Thanks for your report.

The previous webpack settings was problematic and setting the target to `webworker` is correct.
Ideally `joi` could be built to be compatible in a `webworker`, have you maybe checked https://github.com/hapijs/joi/issues/154?

**Comment by EverlastingBugstopper** [comment] 2019-10-28 22:33
@MiroslavPetrik - generally if something is breaking because of the `webworker` target, it is because it will not be supported in the Workers runtime. I'm closing this issue as it is intended behavior.

**Closed by EverlastingBugstopper** 2019-10-28 22:33 UTC
Labels: subject - webpack, user report

**Comment by PierBover** [comment] 2020-03-17 03:14
Facing the same issue with Joi... @MiroslavPetrik did you solve this?

**Comment by EverlastingBugstopper** [comment] 2020-03-17 15:07
@PierBover if you're running into similar issues it's likely because the library you're attempting to use is not compatible with the `webworker` target. Cloudflare Workers are not executed within the context of a Node runtime, nor are they executed within the context of a browser, so some APIs (like `window`, `fs`, and `tls`) are not available and `webpack`/`wrangler build` will fail if you attempt to include them. This is intended behavior and will not change - you'll need to either find another library to use or implement support for the `webworker` target in that library.

**Comment by PierBover** [comment] 2020-03-17 16:04
Thanks @EverlastingBugstopper but yeah that was clear from the previous comments.

Anyway I ended up writing my own validation logic.

**Comment by lostpebble** [comment] 2020-08-13 10:44
I wish CloudFlare would have been more upfront about this very serious disadvantage of webworkers and compiling JS code for it. From the docs you make it sound as if all NPM packages are compatible, but the truth of the matter is **loads** of packages implement something on top of either the native Node.js or browser APIs, or can only be deployed on Node.js because of other native system constraints.

To quote the docs:

> All projects deployed to Cloudflare Workers support NPM packages, which makes it incredibly easy to rapidly build out a lot of functionality in your serverless functions.

Here was me thinking "great!" and spending much of my day trying to deploy my project realizing at the end that most of my code will in fact not be compatible because it relies on NPM modules which are outside of the sandboxed webworker scope.

**Comment by pekado** [comment] 2021-03-04 15:34
> Thanks @EverlastingBugstopper but yeah that was clear from the previous comments.
> 
> Anyway I ended up writing my own validation logic.

Can you show us your validation logic? pleaseeee
