### ISSUE TITLE
Duplicate output files: dist/main.js and workers-site/worker/script.js

### ISSUE THREAD

**Issue by computator** [cloudflare/wrangler#1046] opened 2020-02-12 00:37 UTC
### 🐛 Bug Report

I recently created a workers site, and was looking through the generated files to decide what was temporary and what to commit. I noticed that there were two identical files:
- `dist/main.js`
- `workers-site/worker/script.js`

I spent some time trying to figure out why both existed, and which was the original vs duplicate. From what I can tell, `dist/main.js` is the webpack output, and the other file is a duplicate of it. It seems that at one point, both files existed because some other code was prepended to the webpack output before it was written to `worker/script.js`, but this appears to no longer be the case. It seems to have been removed in e7416ffe4abff5a8b13b40619181f180edae8d1f. Seeing as the two files are redundant and slightly confusing, maybe webpack should be configured to output directly to `worker/script.js` or something instead. The current process seems to have caused #681 as well.

#### Environment

* operating system: Ubuntu 18.04
* output of `rustc -V`: not installed
* output of `node -v`: `v8.10.0`
* output of `wrangler -V`: ` wrangler 1.7.0` (Unrelated: it seems maybe wrangler inserts a space before the version string by accident?)

**Comment by xtuc** [comment] 2020-02-13 19:54
I can confirm that `dist/main.js` is the webpack and `worker/script.js` in the worker. We could technically remove/hide the webpack output by proccessing it in wrangler's memory.

**Comment by TooYoungTooSimp** [comment] 2020-07-24 11:56
Meet the same problem. Hope it can be fix soon.

**Comment by lfender6445** [comment] 2020-09-04 21:44
> I can confirm that dist/main.js is the webpack and worker/script.js in the worker. We could technically remove/hide the webpack output by proccessing it in wrangler's memory.

did you mean to say that  `worker/script.js` is not an artifact of webpack? 

i am wondering in the meantime is it possible to configure webpack config so that output of both files go to single directory, eg `dist`

**Comment by da99** [comment] 2020-11-28 05:26
> i am wondering in the meantime is it possible to configure webpack config so that output of both files go to single directory, eg `dist`

### For the current version of wrangler (v1.12.2): 
The default output file seems to have changed to `dist/worker.js`. 
The output file `worker/script.js` doesn't seem able to be customized at the moment because it is hard-coded in Rust: https://github.com/cloudflare/wrangler/blob/v1.12.2/src/wranglerjs/bundle.rs (lines 13 and 63).

I guess it would be alright to customize the default `dist` output dir to `worker` to keep all files in one place:
```
// file: webpack.config.js
const path = require("path");
module.exports = {
  target: "webworker",
  output: {
    path: path.resolve(__dirname, 'worker/')
  }
}
```
However, I could never figure out why the 2 files are created in 2 different places but with the same content: `worker/script.js` and `dist/worker.js`

**Comment by xortive** [comment] 2021-04-09 13:26
closed by https://github.com/cloudflare/wrangler/pull/1833 (since you can use custom builds to avoid this)

**Closed by xortive** 2021-04-09 13:26 UTC
Labels: sites, webpack
