### ISSUE TITLE
An option to not clear old static files from being served

### ISSUE THREAD

**Issue by osdiab** [cloudflare/wrangler#1540] opened 2020-09-02 06:13 UTC
#### Overview and problem statement

Our company is switching to hosting our site via a `create-react-app` project with code splitting. When a user navigates to a new page they may request a new chunk of the bundle. However, if we do a deploy, and one of these users is still on the old version of the frontend app, they request a bundle that doesn't exist, it 404's and the site breaks.

It would be nice if there was a way to retain the old assets of our site for some time before clearing them out between deploys - we don't do backwards incompatible changes often, and all our scripts have hashes of file content as part of their filenames anyway so assets that change aren't really an issue.

Alternatively can some edge caching policy save us here?

In the meantime we've been reducing these errors by prefetching, and auto triggering refreshes on old bundles.

Cloudflare Support told me to post here, FYI. Thanks for the great infrastructure!

**Comment by ispivey** [comment] 2020-09-02 12:22
@osdiab thanks for the report! We're aware and working through solutions right now – hope to have some updates to share soon.

**Comment by simplenotezy** [comment] 2020-09-18 11:00
Sounds good @ispivey

**Comment by ashleymichal** [comment] 2020-09-18 19:05
this is a duplicate of #1553

**Closed by ashleymichal** 2020-09-18 19:05 UTC
Labels: subject - site, user report
