### ISSUE TITLE
port custom header logic to cloudflare-rs client usage

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#900] opened 2019-11-21 19:45 UTC
At the moment we send user agent headers to track usage of specific features of wrangler based on api calls. this is v. useful, we need to maintain it as we move to cloudflare-rs as our primary api client library.

**Comment by EverlastingBugstopper** [comment] 2019-11-21 19:50
this is a duplicate of #731

**Closed by EverlastingBugstopper** 2019-11-21 19:50 UTC
Labels: category - refactor, priority - critical, status - PR welcome
