### ISSUE TITLE
text binding is not creating in env

### ISSUE THREAD

**Issue by xtuc** [cloudflare/wrangler#1081] opened 2020-02-18 16:29 UTC
#### Environment

* operating system:
* output of `rustc -V`:
* output of `node -v`:
* output of `wrangler -V`:  wrangler 1.8.0-rc.0

#### Steps to reproduce

Wrangler configuration:
```toml
name = "hein"
type = "webpack"
webpack_config = "webpack.config.test.js"

[env.development]
text = { A = "1" }
```

```js
console.log(A)
```

#### What did you expect to see?

```js
console.log("1")
```

which you can get with the the Wrangler configuration:
```toml
name = "hein"
type = "webpack"
webpack_config = "webpack.config.test.js"
text = { A = "1" }

[env.development]
text = { A = "1" }
```

#### What did you see instead?

```
A is not defined
```

**Comment by ashleymichal** [comment] 2020-02-18 17:05
command run?

**Comment by xtuc** [comment] 2020-02-18 17:15
`wrangler publish --env development`

**Comment by EverlastingBugstopper** [comment] 2020-02-18 17:44
Wonder if this repros in latest release - likely has to to do with inheritance

**Comment by calderonth** [comment] 2020-02-18 17:50
I can reproduce in `wrangler 1.8.0-rc.1`.

**Comment by ashleymichal** [comment] 2020-02-18 17:54
@calderonth rc.1 should use the key `vars` rather than `text`, fyi. https://github.com/cloudflare/wrangler/releases/tag/v1.8.0-rc.1

**Comment by EverlastingBugstopper** [comment] 2020-02-18 18:01
it seems to be fixed in latest release @xtuc

**Closed by EverlastingBugstopper** 2020-02-18 18:01 UTC
Labels: user report

**Comment by xtuc** [comment] 2020-02-18 18:10
@calderonth can you please try again and confirm it's working now?

**Comment by calderonth** [comment] 2020-02-19 11:53
Using `vars` fixes it. Thanks.
