### ISSUE TITLE
Error: Something went wrong! Status: 400 Bad Request, 

### ISSUE THREAD

**Issue by sureshkumargondi** [cloudflare/wrangler#1040] opened 2020-02-09 16:35 UTC
#### Environment

* operating system: Mac OS Catalina 
* output of `rustc -V`: 
* output of `node -v`: 13.8.0
* output of `wrangler -V`: 1.7.0

#### Steps to reproduce

Uploaded all the Hugo generated files of 125k around. After the upload, I see this error. 

administrator@static donateers % wrangler publish
🌀  Created namespace for Workers Site "__donateers-workers_sites_assets"
🌀  Uploading site files
██████████████████████████████████████████████████████████████████ 214459/214459
✨  Success
⬇️ Installing wranglerjs...
⬇️ Installing wasm-pack...
✨  Built successfully, built project size is 11 KiB.
Error: Something went wrong! Status: 400 Bad Request, Details {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10027,
      "message": "workers.api.error.script_too_large"
    }
  ],
  "messages": []
}

#### What did you expect to see?
Successful publish static site to workers. 

#### What did you see instead?
workers.api.error.script_too_large. Site got uploaded, but not deploying to the workers.

**Comment by EverlastingBugstopper** [comment] 2020-02-10 16:06
Sorry @sureshkumargondi - you won't be able to use Workers Sites unless you reduce the overall number of files for now. Closing this as a duplicate of #896

**Closed by EverlastingBugstopper** 2020-02-10 16:06 UTC
Labels: user report
