### ISSUE TITLE
__STATIC_CONTENT_MANIFEST missing in env object when using ES modules

### ISSUE THREAD

**Issue by ttraenkler** [cloudflare/wrangler#1938] opened 2021-05-28 14:20 UTC
#### Describe the bug

When using the new ES module syntax and rollup instead of webpack as a bundler, I cannot access the workers-site binding `__STATIC_CONTENT_MANIFEST` neither through the global env variable anymore nor through the new env object.

I have tried using both wrangler 1.16.1 or 1.16.0-durable-objects-rc.0 to upload a workers-site with the same result

#### Reproduce the bug

A list of steps to reproduce the bug.

1. upload a workers-site with the latest wrangler 
2. bundle your worker with rollup using the new ESM syntax
3. try to access the `__STATIC_CONTENT_MANIFEST` as a global variable or in the `env` object -> is undefined

#### Expected behavior

```ts
env.__STATIC_CONTENT_MANIFEST
``` 
should contain the manifest string

#### Environment and versions

Fill out the following information about your environment.

* operating system: MacOS latest
* output of `wrangler -V`: wrangler 1.16.0-durable-objects-rc.0
* output of `node -v`: v14.15.4
* content of `wrangler.toml`:

```toml
account_id = "..."
kv_namespaces = [...]
name = "..."
route = ""
type = "javascript"
vars = {ENVIRONMENT = "production", DEBUG_MODE = false}
workers_dev = true
zone_id = ""

[site]
bucket = "../build"
entry-point = "workers-site"

[durable_objects]
bindings = [{name = "COUNTER", class_name = "Counter"}]

[build]
command = "yarn && yarn build"

[build.upload]
# The "modules" upload format is required for all projects that export a Durable Objects class
dir = "dist"
format = "modules"
main = "./index.mjs"

```

I think the relevant file should be `src/upload/form/mod.rs` in the wrangler repo.
Let me know if you need more information or cannot reproduce the bug without further details. Also please point me to a branch if there is already ongoing work so I could potentially contribute a PR.

**Comment by irvinebroque** [comment] 2021-06-18 19:10
Sample project that reproduces this, I ran into it as well and wanted to confirm it wasn't caused by other configuration in another project:

https://github.com/irvinebroque/repro-kv-asset-handler-modules-issue

**Comment by DrewRidley** [comment] 2021-06-23 22:01
This issue also directly affects the KV handler because the KV handler relies on this environment variable to serve requests. Without wrangler being corrected, my PR submitted over there will not function correctly.

**Comment by xortive** [comment] 2021-06-23 22:25
The necessary work here is to add `__STATIC_CONTENT_MANIFEST` as a text module to the module manifest passed into `ModuleAssets` -- this is the equivalent of a text blob in the service worker format.

It'll be exposed as a module that can be imported, not under `env` however.

**Comment by DrewRidley** [comment] 2021-06-27 04:30
This feature has been completed following the suggested guidelines and can be tracked at the linked PR #1973. I tested it extensively locally and it worked as intended.

**Comment by mikecann** [comment] 2021-07-29 00:01
Very keen for this to go in. It was super confusing when trying to build a Durable Objects project that also uses Sites.

**Comment by threepointone** [comment] 2021-11-16 11:57
This should be fixed in the latest wrangler release. I'll also make a release of kv-asset-handler today (https://github.com/cloudflare/kv-asset-handler/pull/263), so that should close this up. Closing this issue.

**Closed by threepointone** 2021-11-16 11:58 UTC
Labels: bug
