### ISSUE TITLE
Workers Sites default caching behavior unintuitive/confusing

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/wrangler#1208] opened 2020-04-14 21:56 UTC
While building https://github.com/cloudflare/isbgpsafeyet.com I’ve been encountering this difficult issue with caching of assets.

Essentially, every time I update a CSS or JS file located in `/public` (which is referenced by an HTML file in `/public`), I have to manually add `?v=${ NEW++ }` to the src/href in order to prevent a mismatch.

e.g. https://github.com/cloudflare/isbgpsafeyet.com/commit/fd3e6b85e1f4eadf166fae254919f489d58a08ea

If I don’t do this, then after running `wrangler publish` (executed via Github Actions in this case), the new `index.html` document will load in the browser, but the old CSS and JS (and favicon and any other linked asset inside `/public`) will come with it.

If it helps, we started from the Workers Sites template: https://github.com/cloudflare/worker-sites-template.

cc @rita3ko

**Comment by victoriabernard92** [comment] 2020-04-16 18:59
The issue sounds like caching in the browser right? Hard refreshing your browser should fix this. 
I assume it's caching in the browser since caching on the edge uses a manifest that ensures the most recent content is served as the cache key contains a hash of the content. Also you can adjust cache behavior in the kv-asset-handler: https://github.com/cloudflare/kv-asset-handler#cachecontrol

If you are still having trouble what's your wrangler version? Also can you remove the `?v=${ NEW++ }` on a mock site so I can reproduce?

**Comment by adamschwartz** [comment] 2020-04-17 00:57
Thanks so much for sharing that link. That gave me a lot more of an understanding of how this stuff works.

I’m not sure what’s going but asking a user to hard refresh their browser is not a solution to this problem. Our customers (or in this case, visitors of http://isbgpsafeyet.com) will see a broken site without any understanding as to why; they may assume the site is broken and leave without trying to refresh the page.

Even adding the query params I’ve seen it happen that the client will get the `index.js` file the most recent `wrangler publish` with the `index.css` from a publish hours before. To me that sounds like it could be the [`edgeTTL` property](https://github.com/cloudflare/kv-asset-handler#edgettl) from your link. If that’s the case I’d be very surprised and confused that the query params were not causing the edge to treat the request as new.

**Comment by zackbloom** [comment] 2020-04-17 03:05
I ended up grafting a pretty heavy-weight build system into the site to fix this: https://github.com/cloudflare/isbgpsafeyet.com/pull/14/files

I believe the site's default caching would put files in cache for way too long. Without some way of versioning files as they are emitted there is no way that they wouldn't be invalidated irregularly. I have to believe this is breaking virtually every Worker's Site which uses multiple files on deploy for a period of time.

**Comment by rita3ko** [comment] 2020-04-17 03:54
@zackbloom I don't think it's an issue of files being put in cache for too long — I think TTLs are based on recommendations from Lighthouse (if you cache for shorter, can't get that 100!). 

This is a non-issue if you're using a static site / frontend framework like Gatsby or create-react-app with Workers since it appends a shasum which breaks up the cache whenever you update, and built. However, I can see how we're not setting people up for success with the default static site template that you get when you run `wrangler generate --site`. I couldn't find the repo for the template — @ashleygwilliams do you know where this lives? I wonder if we want to have our own in the first place over picking something like create-react-app by default since it will set people up for problems like this.

**Comment by rita3ko** [comment] 2020-04-17 03:58
Found it (not sure why it didn't show up when I searched Cloudflare GH)... Anyway, this is the default Workers Sites worker https://github.com/cloudflare/worker-sites-template

**Comment by zackbloom** [comment] 2020-04-17 04:09
I am with you, I think if we want to include a versioning tool in the default template it would go a long way. Ideally, of course, there would be a way to run both the build on the sites files, and on the Worker, with Wrangler somehow. For this project I wrote a runner to invoke `webpack --watch` and `wrangler dev` simultaneously but I doubt most people will:

![image](https://user-images.githubusercontent.com/55347/79531139-14dff680-8037-11ea-92d2-62d5024b5dcf.png)

An alternative option would be for Wrangler to examine html files and version the JS and CSS files they reference.

**Comment by victoriabernard92** [comment] 2020-04-17 16:51
> An alternative option would be for Wrangler to examine html files and version the JS and CSS files they reference.

@zackbloom  I believe what you're asking is already happening through the asset manifest which hashes the JS and CSS content that will be used as a key to be cached on Cloudflare. Every time you upload the files the asset manifest is updated.

Testing this I see browser cache is not set. Can you add in the worker `browserTTL: 0` before calling the `getAssetFromKV` and see if this fixes the issue?

**Comment by zackbloom** [comment] 2020-04-17 17:03
Hi @victoriabernard92! I would love to understand that more. So are we caching the JS and CSS and then creating a cache tag which all the files are then uploaded under? How do we purge the old cache tag on the next deploy?

**Comment by victoriabernard92** [comment] 2020-04-17 17:14
it doesn't need to get purged since it's under a cache key that no one will have the key to

For example what cache and kv will look like with `123HASHBROWN` being a hash of the content :
```
  'key1.123HASHBROWN.txt': 'val1',
  'index.123HASHBROWN.html': 'cache me if you can',
```

KV asset handler then maps requests to these keys
```
/ -> index.123HASHBROWN.html
```

Blog has some details and nice illustrations see https://blog.cloudflare.com/extending-the-workers-platform/

**Comment by ashleymichal** [comment] 2020-04-17 17:46
this is a couple  of different issues; one is with the default browser cache behavior, and one is a potential feature for wrangler. for some background:

workers sites was designed with modern static site generators in mind; most if not all of these implement the same kind of cache-busting file fingerprinting that inspired wrangler's asset manifest, which uses content hashing to update the names of these assets wherever they are referenced in the site as part of the build step (effectively what @zackbloom has implemented using webpack). Projects like this work just fine. However, a static site which does not employ this method will not benefit from this cache-busting behavior in the browser; only on the edge. The default template has no build step to update these references, and so has this problem.

Proposed multi step solution:

1. in the short term, set the default browser ttl to zero in the workers sites template; this loses the efficiency of browser-side caching but ensures always up to date assets. This issue would need to be handled in kv-asset-handler.

2. add an optional field under the `[site]` config in wrangler.toml (strawman name) `static_cached_assets`: an optional array of glob paths for assets that should be cached by the browser. Assets specified by these paths MUST include a content-based hash in their filenames. This would deterministically create exceptions for the above browser caching behavior, allowing these assets to be cached by the browser. This issue would need to be addressed in both kv-asset-handler AND wrangler.

I am skeptical about implementing our own static site building logic, as this is a relatively complex problem around which many tools already exist with robust ecosystems and maintenance teams of their own, and I don't believe our team has the bandwidth to maintain something like this. i would welcome a user-maintained template to this effect, but would caution against maintaining our own blessed version.

**Comment by victoriabernard92** [comment] 2020-04-17 18:23
@ashleymichal 
We talked about `1.` before but decided to rely on browser's default cache behavior (i.e. CSS and JS will get cached but not HTML) by not inserting any `cache-control`. Users complained about it when we turned browser caching off for CSS and JS by default. I don't think more comments will help solve this issue because it doesn't seem users are using the comments . e.g. Zack deleted this line but for some reason didn't modify those options https://github.com/cloudflare/isbgpsafeyet.com/pull/14/files#diff-a7c5cb691bcea8b2aff31bb0756a2d28L43 

I would propose in the template we set `DEBUG= true` by default and make the default options be just turning browser cache off (e.g. `browserTTL: 0`) but that doesn't solve the issue of users wanting default browser cache behavior. Maybe a console.warn that they are in DEBUG mode? 

`2.` I think will exacerbate the underline problem that users don't know how/where wrangler/kv-asset-handler caching behavior lives or how to modify it. Also we really don't want to support more caching options as cache best practices get real complicated real fast.

**Closed** 2020-07-04 21:18 UTC
Labels: subject - site, wontfix

**Comment by kokarn** [comment] 2021-03-10 11:10
I know this is stale and sorry if I'm necromancing here, but searched for a while to find this topic.

```
This is a non-issue if you're using a static site / frontend framework like Gatsby or create-react-app with Workers since it appends a shasum which breaks up the cache whenever you update, and built. 
```
There's one major concern that hasn't been solved here, and that's the issue that index.html _doesn't_ contain a hash.
It's true that all css & js does, but since the loader-page doesn't there's quite a big issue on any setup adding some sort of caching.

The index.html page might be loaded by the browser cache, and then referencing items that don't exist. The reload/refresh idea above does solve this, but that's very unintuitive for the end-user.

I'm not sure if this is something Wrangler itself can fix? Probably not? But I'm adding my comment here after searching for _days_ on wtf was going on :D

**Comment by AlexanderBich** [comment] 2021-07-01 14:20
> I know this is stale and sorry if I'm necromancing here, but searched for a while to find this topic.
> 
> ```
> This is a non-issue if you're using a static site / frontend framework like Gatsby or create-react-app with Workers since it appends a shasum which breaks up the cache whenever you update, and built. 
> ```
> 
> There's one major concern that hasn't been solved here, and that's the issue that index.html _doesn't_ contain a hash.
> It's true that all css & js does, but since the loader-page doesn't there's quite a big issue on any setup adding some sort of caching.
> 
> The index.html page might be loaded by the browser cache, and then referencing items that don't exist. The reload/refresh idea above does solve this, but that's very unintuitive for the end-user.
> 
> I'm not sure if this is something Wrangler itself can fix? Probably not? But I'm adding my comment here after searching for _days_ on wtf was going on :D

@kokarn 
What about overwriding index.js inside workers-site with appropriate rules for not caching .html files?
Here's my example for Gatsby:
https://gist.github.com/AlexanderBich/7bef9d731a9b569b7fea51f2cccd62a1

**Comment by kokarn** [comment] 2021-07-10 08:48
That's a good suggestion that at least might improve it. I guess the only scenario left where this wouldn't help is when something misbehaves in any proxy service and that should be reasonable rare
