### ISSUE TITLE
Waiting for API token - Keep loading loading... 

### ISSUE THREAD

**Issue by sureshkumargondi** [cloudflare/wrangler#1993] opened 2021-07-13 18:19 UTC
#### Describe the bug

I have intstalled packaged on my m1 macbook pro. Wrnagler using brew and node and all. 

When I start to authenticate the process of using the command 

wrangler login  

I did typed yes.. Authenticated 

But.. in the terminal, it keeps on loading with a message of "waiting for API token .."

A clear and concise description of the bug.

#### Reproduce the bug

A list of steps to reproduce the bug.

1. install node and wrangler from the brew package manager
2. Start the initial process of connecting the local to the Cloudflare account. 
3. Use the command wrangler login  
4. Press y
5. Authenticate it on the browser
6. The terminal keep showing ... waiting for the API token

#### Expected behavior

Connected the local machine to Cloudflare account with the API token. But.. itsn't happened. 

#### Environment and versions

Fill out the following information about your environment.

* operating system: Mac OS Big sur 11.04
* output of `wrangler -V`: wrangler 1.17.0
* output of `node -v`: v16.4.2
* content of `wrangler.toml`: Nothing so far.

**Comment by nilslice** [comment] 2021-07-13 18:30
Hi @sureshkumargondi, closing this as a duplicate of #1703 but thank you for reporting! 

Can you confirm that you were _already_ logged into the browser when `wrangler` opened up the browser window. If you needed to sign-in, please repeat this process so `wrangler` opens up a browser which has a pre-existing authenticated session to dash.cloudflare.com 

We are working on improvements to this workflow, so your feedback is helpful!

**Closed by nilslice** 2021-07-13 18:30 UTC
Labels: bug

**Comment by sureshkumargondi** [comment] 2021-07-13 18:37
Hey, @nilslice I'm able to log into the browser if I repeat the process again. 

So it asked for the first time alone.

Hope this helps you.
